"""Additive registries for H3 episode trailers.

Stories stay as `minimaxh3/episodes/<slug>/episode.json`. Do not edit this file
to add a plot. Copy `_template` (or an adult pack) and change the JSON.

Add a camera here: one key + lock + angles.
Add a speed/quality tradeoff here: one key + LoRA stack + steps + sampler.
Add a connect mode here: one key + how GPU beats are wired (T2V cut / prev-last
I2V / authored landing still).

Cinema LoRA is not a preset (heavy, slow). Combat is never a preset; fight
beats opt in with extra_loras: ["combat"].
"""

from __future__ import annotations

from typing import Any

# Default when a T2V episode omits render.camera_pack.
DEFAULT_CAMERA_PACK = "side2d"
DEFAULT_CONNECT = "t2v"

# Positive phrasing only. Named "slow motion" (even negated) still gets drawn.
CAMERA_PACKS: dict[str, dict[str, Any]] = {
    "side2d": {
        "label_ja": "横スク",
        "hint_ja": "迷ったらこれ。常に真横・全身・2D横スクロール。",
        "lock": (
            "Locked side-on 2D side-scroller third-person gameplay camera at hip-to-shoulder height. "
            "Both adults stay full body including feet. The camera stays in the side plane and tracks "
            "only left and right on a straight line at real-time game speed"
        ),
        "angles": (
            "locked side-on wide at hip height, both adults full body including feet, horizontal track only",
            "locked side-on at shoulder height, a half-step closer, both adults full body including feet, same side plane",
            "locked side-on further back so more floor shows, hip height, both adults full body including feet, horizontal track only",
            "locked side-on at desk height, both adults full body, same side plane, slight horizontal track",
            "locked side-on wide at chest height, both adults full body including feet, camera holds then tracks left and right",
        ),
    },
    "action3d": {
        "label_ja": "3Dアクション",
        "hint_ja": "引きの三人称。カットつなぎのときショットごとに回る。",
        "lock": (
            "Pulled-back third-person 3D-action gameplay camera. Both adults stay full body including feet. "
            "The camera stays behind or beside the player at hip-to-shoulder height at real-time game speed"
        ),
        "angles": (
            "behind-left three-quarter at shoulder height, pulled back, both adults full body including feet",
            "behind-right three-quarter at hip height, pulled back, both adults full body including feet",
            "high three-quarter over the aisle, pulled back, both adults full body including feet",
            "low three-quarter at hip height tracking the lead adult, both adults full body including feet",
            "side-rear three-quarter at shoulder height, pulled back, both adults full body including feet",
        ),
    },
}

CAMERA_ALIASES: dict[str, str] = {
    "横スク": "side2d",
    "2D横スク": "side2d",
    "サイド": "side2d",
    "2d": "side2d",
    "side-scroll": "side2d",
    "3Dアクション": "action3d",
    "3d": "action3d",
    "action": "action3d",
}

# t2v = each clip is independent (prompt can correct; cameras may change).
# chain = beat 2+ I2V from the previous clip's last frame (seamless, harder to restyle).
# landing = beat 2+ I2V onto an authored still as Picture 2 (needs stills/).
CONNECT_MODES: dict[str, dict[str, Any]] = {
    "t2v": {
        "label_ja": "カット",
        "hint_ja": "迷ったらこれ。本ごとに撮り直し可。カメラを変えられる。",
        "rotate_camera": True,
    },
    "chain": {
        "label_ja": "前の尻から続ける",
        "hint_ja": "2本目以降は前クリップの最終フレームから I2V。つながり優先。",
        "rotate_camera": False,
    },
    "landing": {
        "label_ja": "着地スチールへ着く",
        "hint_ja": "用意した jpg を最後のコマにする I2V。スチールがある本だけ。",
        "rotate_camera": False,
    },
}

CONNECT_ALIASES: dict[str, str] = {
    "カット": "t2v",
    "cut": "t2v",
    "t2v_cut": "t2v",
    "独立": "t2v",
    "前の尻から続ける": "chain",
    "i2v_chain": "chain",
    "last-frame": "chain",
    "prev-last": "chain",
    "連鎖": "chain",
    "着地スチールへ着く": "landing",
    "i2v_landing": "landing",
    "still_as_last": "landing",
    "landing-still": "landing",
    "着地": "landing",
}

# User-facing names. Aliases keep older episode.json valid.
# stack entries are (lora_key, strength, optional). Larry never stacks with LightX2V turbo.
PRESET_CANON: dict[str, dict[str, Any]] = {
    "speed": {
        "label_ja": "スピード",
        "hint_ja": "最速。turbo 4step。格闘 LoRA は積まない。",
        "stack": [("turbo4", 1.0, False)],
        "steps": 4,
        "trigger": "",
        "sampler": "euler",
        "scheduler": "simple",
    },
    "balance": {
        "label_ja": "バランス",
        "hint_ja": "迷ったらこれ。Larry 8step。",
        "stack": [("larry", 1.0, False)],
        "steps": 8,
        "trigger": "",
        "sampler": "euler",
        "scheduler": "simple",
    },
    "quality": {
        "label_ja": "質",
        "hint_ja": "きれい優先。Larry 12step。時間はかかる。",
        "stack": [("larry", 1.0, False)],
        "steps": 12,
        "trigger": "",
        "sampler": "euler",
        "scheduler": "beta",
    },
}

PRESET_ALIASES: dict[str, str] = {
    "fast": "speed",
    "preview": "speed",
    "daily": "balance",
    "スピード": "speed",
    "スピード優先": "speed",
    "バランス": "balance",
    "質": "quality",
    "質優先": "quality",
}


def expand_presets() -> dict[str, dict[str, Any]]:
    out = dict(PRESET_CANON)
    for alias, canon in PRESET_ALIASES.items():
        if alias.isascii() and alias.isalpha() and alias not in out:
            out[alias] = PRESET_CANON[canon]
    return out


def canonical_preset(name: str) -> str:
    raw = str(name or "").strip()
    if raw in PRESET_CANON:
        return raw
    return PRESET_ALIASES.get(raw, raw)


def canonical_camera(name: str) -> str:
    raw = str(name or "").strip()
    if raw in CAMERA_PACKS:
        return raw
    return CAMERA_ALIASES.get(raw, raw)


def canonical_connect(name: str) -> str:
    raw = str(name or "").strip()
    if not raw:
        return ""
    if raw in CONNECT_MODES:
        return raw
    return CONNECT_ALIASES.get(raw, raw)


def ui_choices(kind: str) -> list[str]:
    """Japanese labels for Colab dropdowns, in display order."""
    if kind == "connect":
        return [str(CONNECT_MODES[k]["label_ja"]) for k in CONNECT_MODES]
    if kind == "camera":
        return [str(CAMERA_PACKS[k]["label_ja"]) for k in CAMERA_PACKS]
    if kind == "preset":
        return [str(PRESET_CANON[k]["label_ja"]) for k in PRESET_CANON]
    raise KeyError(kind)


def describe_run(*, connect: str = "", camera: str = "", preset: str = "", episode: str = "") -> str:
    """One short Japanese block for the Colab form: what was chosen and when to pick something else."""
    c_key = canonical_connect(connect) or DEFAULT_CONNECT
    cam_key = canonical_camera(camera) or DEFAULT_CAMERA_PACK
    p_key = canonical_preset(preset) or "balance"
    c = CONNECT_MODES.get(c_key) or CONNECT_MODES[DEFAULT_CONNECT]
    cam = CAMERA_PACKS.get(cam_key) or CAMERA_PACKS[DEFAULT_CAMERA_PACK]
    p = PRESET_CANON.get(p_key) or PRESET_CANON["balance"]
    head = f"一発 {episode}".strip() if episode else "一発"
    return (
        f"{head}\n"
        f"  1 つなぎ  {c['label_ja']}  — {c['hint_ja']}\n"
        f"  2 カメラ  {cam['label_ja']}  — {cam['hint_ja']}\n"
        f"  3 画質    {p['label_ja']}  — {p['hint_ja']}\n"
        "迷ったらこの3つの既定のままで Run all。"
    )
