"""Additive registries for H3 episode trailers.

Stories stay as `minimaxh3/episodes/<slug>/episode.json`. Do not edit this file
to add a plot. Copy `_template` (or an adult pack) and change the JSON.

Add a camera here: one key + lock + angles.
Add a speed/quality tradeoff here: one key + LoRA stack + steps + sampler.
Add a connect mode here: one key + how GPU beats are wired (T2V cut / prev-last
I2V / authored landing still).

Cinema LoRA is not a preset (heavy, slow). Combat is never a preset; fight
beats opt in with extra_loras: ["combat"].

Colab shows `choice_ja` in the dropdown. `when_ja` is the one-line "pick this when".
`label_ja` is the short name printed at run start. Keep those three in this file so
the form cannot drift from the engine.
"""

from __future__ import annotations

from typing import Any

# Default when a T2V episode omits render.camera_pack.
DEFAULT_CAMERA_PACK = "side2d"
DEFAULT_CONNECT = "t2v"

# Positive phrasing only. Named "slow motion" (even negated) still gets drawn.
CAMERA_PACKS: dict[str, dict[str, Any]] = {
    "side2d": {
        "label_ja": "横スク",
        "choice_ja": "横スク（真横・全身・迷ったらこれ）",
        "when_ja": "常に真横の 2D 横スクロール",
        "hint_ja": "迷ったらこれ。常に真横・全身・2D横スクロール。",
        "recommend": True,
        "lock": (
            "Locked side-on 2D side-scroller third-person gameplay camera at hip-to-shoulder height. "
            "Both adults stay full body including feet. The camera stays in the side plane and tracks "
            "only left and right on a straight line at brisk walking game speed"
        ),
        "angles": (
            "locked side-on wide at hip height, both adults full body including feet, horizontal track only",
            "locked side-on at shoulder height, a half-step closer, both adults full body including feet, same side plane",
            "locked side-on further back so more floor shows, hip height, both adults full body including feet, horizontal track only",
            "locked side-on at desk height, both adults full body, same side plane, slight horizontal track",
            "locked side-on wide at chest height, both adults full body including feet, camera holds then tracks left and right",
        ),
    },
    "action3d": {
        "label_ja": "3Dアクション",
        "choice_ja": "3Dアクション（引きの三人称）",
        "when_ja": "引きの三人称。カットつなぎのとき画角が回る",
        "hint_ja": "引きの三人称。カットつなぎのときショットごとに回る。",
        "lock": (
            "Pulled-back third-person 3D-action gameplay camera. Both adults stay full body including feet. "
            "The camera stays behind or beside the player at hip-to-shoulder height at brisk walking game speed"
        ),
        "angles": (
            "behind-left three-quarter at shoulder height, pulled back, both adults full body including feet",
            "behind-right three-quarter at hip height, pulled back, both adults full body including feet",
            "high three-quarter over the aisle, pulled back, both adults full body including feet",
            "low three-quarter at hip height tracking the lead adult, both adults full body including feet",
            "side-rear three-quarter at shoulder height, pulled back, both adults full body including feet",
        ),
    },
}

# t2v = every GPU beat is T2V including the first (prompt can correct; cameras may change).
# chain = first GPU beat T2V, beat 2+ I2V from the previous clip's last frame.
# landing = beat 2+ I2V onto an authored still as Picture 2 (needs stills/).
CONNECT_MODES: dict[str, dict[str, Any]] = {
    "t2v": {
        "label_ja": "カット",
        "choice_ja": "カット（本ごと独立・迷ったらこれ）",
        "when_ja": "1本目から全部 T2V。プロンプトで直したい。カメラも変えられる",
        "hint_ja": "迷ったらこれ。1本目も T2V。本ごとに撮り直し可。カメラを変えられる。",
        "recommend": True,
        "rotate_camera": True,
    },
    "chain": {
        "label_ja": "前の最終フレームから",
        "choice_ja": "前の最終フレームから続ける",
        "when_ja": "1本目は T2V。2本目以降を前クリップの最後のコマから I2V。つながり優先",
        "hint_ja": "1本目は T2V。2本目以降は前クリップの最終フレームから I2V。つながり優先。",
        "rotate_camera": False,
    },
    "landing": {
        "label_ja": "用意した最終フレームへ",
        "choice_ja": "用意した最終フレームへ着く",
        "when_ja": "stills の jpg を最後のコマにする。jpg がある話だけ",
        "hint_ja": "用意した jpg を最後のコマにする I2V。スチールがある本だけ。",
        "rotate_camera": False,
    },
}

# User-facing names. Aliases keep older episode.json valid.
# stack entries are (lora_key, strength, optional). Larry never stacks with LightX2V turbo.
PRESET_CANON: dict[str, dict[str, Any]] = {
    "speed": {
        "label_ja": "スピード",
        "choice_ja": "スピード（最速）",
        "when_ja": "試し打ち。turbo 4step。格闘 LoRA なし",
        "hint_ja": "最速。turbo 4step。格闘 LoRA は積まない。",
        "stack": [("turbo4", 1.0, False)],
        "steps": 4,
        "trigger": "",
        "sampler": "euler",
        "scheduler": "simple",
    },
    "balance": {
        "label_ja": "バランス",
        "choice_ja": "バランス（迷ったらこれ）",
        "when_ja": "普段使い。この UNet では LoRA なし euler 8",
        "hint_ja": "迷ったらこれ。LoRA なし euler 8。Larry は積まない。",
        "recommend": True,
        "stack": [("larry", 1.0, False)],
        "steps": 8,
        "trigger": "",
        "sampler": "euler",
        "scheduler": "simple",
    },
    "quality": {
        "label_ja": "質",
        "choice_ja": "質（きれい・時間かかる）",
        "when_ja": "きれい優先。この UNet では LoRA なし euler 12",
        "hint_ja": "きれい優先。LoRA なし euler 12。時間はかかる。",
        "stack": [("larry", 1.0, False)],
        "steps": 12,
        "trigger": "",
        "sampler": "euler",
        "scheduler": "beta",
    },
}


def _label_aliases(registry: dict[str, dict[str, Any]], extra: dict[str, str]) -> dict[str, str]:
    """Map short names, dropdown strings, and leftover English onto canonical keys."""
    out = dict(extra)
    for key, spec in registry.items():
        for name in (spec.get("label_ja"), spec.get("choice_ja")):
            text = str(name or "").strip()
            if text:
                out[text] = key
    return out


CAMERA_ALIASES: dict[str, str] = _label_aliases(
    CAMERA_PACKS,
    {
        "2D横スク": "side2d",
        "サイド": "side2d",
        "2d": "side2d",
        "side-scroll": "side2d",
        "3d": "action3d",
        "action": "action3d",
    },
)

CONNECT_ALIASES: dict[str, str] = _label_aliases(
    CONNECT_MODES,
    {
        "cut": "t2v",
        "t2v_cut": "t2v",
        "独立": "t2v",
        "i2v_chain": "chain",
        "last-frame": "chain",
        "prev-last": "chain",
        "連鎖": "chain",
        "前の尻から続ける": "chain",
        "最終フレームi2v": "chain",
        "i2v_landing": "landing",
        "still_as_last": "landing",
        "landing-still": "landing",
        "着地": "landing",
        "着地スチールへ着く": "landing",
        "最終フレーム用意": "landing",
    },
)

# Combat V2 is optional. Default off. On = High-Memory only (VRAM 70+ or RAM 60+).
COMBAT_MODES: dict[str, dict[str, Any]] = {
    "off": {
        "label_ja": "オフ",
        "choice_ja": "格闘LoRAオフ（迷ったらこれ）",
        "when_ja": "行為ルート。戦いなし。後背位とベロチュー。A100 40GB はこれ",
        "hint_ja": "迷ったらこれ。話は行為。Combat は積まない。",
        "recommend": True,
    },
    "on": {
        "label_ja": "オン",
        "choice_ja": "格闘LoRAオン（ハイメモリ専用）",
        "when_ja": "戦いルート。06と10が横スク。話も切り替わる。ハイメモリ専用",
        "hint_ja": "ハイメモリ専用。話は戦い。06と10に Combat。足りないと LoRA だけ落ちる。",
    },
}

COMBAT_ALIASES: dict[str, str] = _label_aliases(
    COMBAT_MODES,
    {
        "combat": "on",
        "combat_on": "on",
        "highmem": "on",
        "ハイメモリ": "on",
        "なし": "off",
        "しない": "off",
        "no-combat": "off",
    },
)

# Hospital-exit story pack. Body JSON is ○受け入れる. Other futures are on_* overlays.
# Kasumi has no on_* keys; this dropdown is ignored there.
STORY_MODES: dict[str, dict[str, Any]] = {
    "accept": {
        "label_ja": "受け入れる",
        "choice_ja": "○受け入れる（生存・完了・迷ったらこれ）",
        "when_ja": "戸惑いながら身体を張って出口へ。ミッション完了",
        "hint_ja": "迷ったらこれ。生存セックス。接合のまま出口。Combat なし",
        "recommend": True,
        "combat": "off",
        "complete": True,
        "menu_selected": 1,
    },
    "invite": {
        "label_ja": "誘う",
        "choice_ja": "□誘う（淫欲・失敗）",
        "when_ja": "こちらから攻める濃厚セックス。院内で淫欲に呑まれて失敗",
        "hint_ja": "ノリノリ。各シーンのあと次へ行ける。最後だけ失敗。Combat なし",
        "combat": "off",
        "complete": False,
        "fail_reason": "淫欲に呑まれた",
        "menu_selected": 2,
    },
    "evade": {
        "label_ja": "回避",
        "choice_ja": "×回避（出口・完了）",
        "when_ja": "エロを避けて一人で出口。ミッション完了",
        "hint_ja": "行為なし。すり抜け。Combat なし",
        "combat": "off",
        "complete": True,
        "menu_selected": 3,
    },
    "fight_win": {
        "label_ja": "戦って勝つ",
        "choice_ja": "△戦って勝つ（完了・ハイメモリ）",
        "when_ja": "れいを倒して出口。みきは回避。かなはすり抜け。しのを倒す。ハイメモリ",
        "hint_ja": "06と10に Combat。しのを倒す。敗北Hなし",
        "combat": "on",
        "complete": True,
        "menu_selected": 0,
    },
    "fight_lose": {
        "label_ja": "戦って負ける",
        "choice_ja": "△戦って負ける（敗北H・失敗・ハイメモリ）",
        "when_ja": "かなに倒されて専用敗北H。ミッション失敗。ハイメモリ",
        "hint_ja": "10でしのに敗北。12が敗北H。出られない",
        "combat": "on",
        "complete": False,
        "fail_reason": "感染者に倒された",
        "menu_selected": 0,
    },
}

STORY_OVERLAY_KEYS: dict[str, str] = {
    "invite": "on_invite",
    "evade": "on_evade",
    "fight_win": "on_fight_win",
    "fight_lose": "on_fight_lose",
}

STORY_ALIASES: dict[str, str] = _label_aliases(
    STORY_MODES,
    {
        "受け入れる": "accept",
        "誘う": "invite",
        "回避": "evade",
        "戦う": "fight_win",
        "勝ち": "fight_win",
        "負け": "fight_lose",
        "敗北": "fight_lose",
        "敗北H": "fight_lose",
        "survival": "accept",
        "lust": "invite",
        "escape": "evade",
        "win": "fight_win",
        "lose": "fight_lose",
    },
)


# Invite pose (hospital □誘う only). Kasumi has no invite_pose_* keys; ignored there.
INVITE_POSE_MODES: dict[str, dict[str, Any]] = {
    "all_fours": {
        "label_ja": "四つん這い",
        "choice_ja": "四つん這い股広げ（迷ったらこれ）",
        "when_ja": "その場で四つん這い、股を広げて誘う",
        "hint_ja": "迷ったらこれ。あやが四つん這いで股を広げる",
        "recommend": True,
    },
    "m_open": {
        "label_ja": "M字",
        "choice_ja": "M字開脚仰向け",
        "when_ja": "仰向けでM字に開いて誘う",
        "hint_ja": "あやが仰向けM字。相手が前から入る",
    },
    "ride": {
        "label_ja": "騎乗位",
        "choice_ja": "ベロチュー→じゅぼ→騎乗位",
        "when_ja": "笑って抱きつき、ベロチュー、じゅぼ、押し倒して騎乗位",
        "hint_ja": "濃い誘う。竿なしのみきはじゅぼの代わりにクンニ",
    },
}

INVITE_POSE_OVERLAY_KEYS: dict[str, str] = {
    "all_fours": "invite_pose_all_fours",
    "m_open": "invite_pose_m_open",
    "ride": "invite_pose_ride",
}

INVITE_POSE_ALIASES: dict[str, str] = _label_aliases(
    INVITE_POSE_MODES,
    {
        "四つん這い": "all_fours",
        "四つん這い股広げ": "all_fours",
        "all-fours": "all_fours",
        "doggy": "all_fours",
        "M字": "m_open",
        "M字開脚": "m_open",
        "m字": "m_open",
        "missionary": "m_open",
        "騎乗位": "ride",
        "cowgirl": "ride",
        "jupo": "ride",
    },
)

# Optional toilet between みき and れい. Any choice continues to the next scene.
TOILET_MODES: dict[str, dict[str, Any]] = {
    "off": {
        "label_ja": "行かない",
        "choice_ja": "トイレに行かない（迷ったらこれ）",
        "when_ja": "道中は廊下のまま。次はれい",
        "hint_ja": "迷ったらこれ。04はれいの登場",
        "recommend": True,
    },
    "pee": {
        "label_ja": "小便",
        "choice_ja": "トイレ・小便",
        "when_ja": "汚い多目的トイレの洋式に座って小便。どれでも次へ",
        "hint_ja": "洋式に座って小便。次はれい（または次の登場）",
    },
    "masturbate": {
        "label_ja": "オナニー",
        "choice_ja": "トイレ・オナニー",
        "when_ja": "同じ便座でオナニー。どれでも次へ",
        "hint_ja": "洋式に座ってオナニー。次へ進む",
    },
    "tentacle": {
        "label_ja": "触手",
        "choice_ja": "トイレ・触手",
        "when_ja": "便器から出た触手がマンコと肛門。どれでも次へ",
        "hint_ja": "触手がマンコと肛門。次へ進む",
    },
}

TOILET_OVERLAY_KEYS: dict[str, str] = {
    "pee": "on_toilet_pee",
    "masturbate": "on_toilet_masturbate",
    "tentacle": "on_toilet_tentacle",
}

TOILET_ALIASES: dict[str, str] = _label_aliases(
    TOILET_MODES,
    {
        "行かない": "off",
        "なし": "off",
        "skip": "off",
        "小便": "pee",
        "おしっこ": "pee",
        "pee": "pee",
        "オナニー": "masturbate",
        "onanii": "masturbate",
        "触手": "tentacle",
        "tentacles": "tentacle",
    },
)

HOSPITAL_ENCOUNTERS: tuple[str, ...] = ("miki", "rei", "kana", "shino")
DEFAULT_APPEAR: dict[str, bool] = {name: True for name in HOSPITAL_ENCOUNTERS}

APPEAR_ALIASES: dict[str, str] = {
    "みき": "miki",
    "れい": "rei",
    "かな": "kana",
    "しの": "shino",
}


PRESET_ALIASES: dict[str, str] = _label_aliases(
    PRESET_CANON,
    {
        "fast": "speed",
        "preview": "speed",
        "daily": "balance",
        "スピード優先": "speed",
        "質優先": "quality",
    },
)


def expand_presets() -> dict[str, dict[str, Any]]:
    out = dict(PRESET_CANON)
    for alias, canon in PRESET_ALIASES.items():
        if alias.isascii() and alias.isalpha() and alias not in out:
            out[alias] = PRESET_CANON[canon]
    return out


def canonical_preset(name: str) -> str:
    raw = str(name or "").strip()
    if raw in PRESET_CANON:
        return raw
    return PRESET_ALIASES.get(raw, raw)


def canonical_camera(name: str) -> str:
    raw = str(name or "").strip()
    if raw in CAMERA_PACKS:
        return raw
    return CAMERA_ALIASES.get(raw, raw)


def canonical_connect(name: str) -> str:
    raw = str(name or "").strip()
    if not raw:
        return ""
    if raw in CONNECT_MODES:
        return raw
    return CONNECT_ALIASES.get(raw, raw)


def canonical_combat(name: str) -> str:
    raw = str(name or "").strip()
    if not raw:
        return ""
    if raw in COMBAT_MODES:
        return raw
    return COMBAT_ALIASES.get(raw, raw)


def canonical_story(name: str) -> str:
    raw = str(name or "").strip()
    if not raw:
        return ""
    if raw in STORY_MODES:
        return raw
    return STORY_ALIASES.get(raw, raw)


def canonical_invite_pose(name: str) -> str:
    raw = str(name or "").strip()
    if not raw:
        return ""
    if raw in INVITE_POSE_MODES:
        return raw
    return INVITE_POSE_ALIASES.get(raw, raw)


def canonical_toilet(name: str) -> str:
    raw = str(name or "").strip()
    if not raw:
        return ""
    if raw in TOILET_MODES:
        return raw
    return TOILET_ALIASES.get(raw, raw)


def canonical_encounter(name: str) -> str:
    raw = str(name or "").strip().lower()
    if not raw:
        return ""
    if raw in HOSPITAL_ENCOUNTERS:
        return raw
    return APPEAR_ALIASES.get(raw, raw)


def parse_appear(raw: str | dict[str, Any] | None) -> dict[str, bool]:
    """Which hospital encounters to keep. Empty / missing = all four appear."""
    out = dict(DEFAULT_APPEAR)
    if raw in (None, "", True):
        return out
    if raw is False:
        return {name: False for name in HOSPITAL_ENCOUNTERS}
    if isinstance(raw, dict):
        for key, value in raw.items():
            enc = canonical_encounter(str(key))
            if enc in out:
                out[enc] = bool(value)
        return out
    text = str(raw).strip()
    if not text:
        return out
    if text.lower() in ("all", "全員", "*"):
        return out
    if text.lower() in ("none", "nobody", "0", "なし"):
        return {name: False for name in HOSPITAL_ENCOUNTERS}
    if "," in text or " " in text.replace(",", " "):
        wanted = {canonical_encounter(part) for part in text.replace(",", " ").split() if part.strip()}
        wanted.discard("")
        if wanted:
            return {name: name in wanted for name in HOSPITAL_ENCOUNTERS}
    return out


def _registry(kind: str) -> dict[str, dict[str, Any]]:
    if kind == "connect":
        return CONNECT_MODES
    if kind == "camera":
        return CAMERA_PACKS
    if kind == "preset":
        return PRESET_CANON
    if kind == "combat":
        return COMBAT_MODES
    if kind == "story":
        return STORY_MODES
    if kind == "invite_pose":
        return INVITE_POSE_MODES
    if kind == "toilet":
        return TOILET_MODES
    raise KeyError(kind)


def ui_choices(kind: str) -> list[str]:
    """Japanese dropdown strings for Colab, in display order."""
    return [str(spec.get("choice_ja") or spec["label_ja"]) for spec in _registry(kind).values()]


def ui_default(kind: str) -> str:
    """The recommended dropdown value (迷ったらこれ)."""
    for spec in _registry(kind).values():
        if spec.get("recommend"):
            return str(spec.get("choice_ja") or spec["label_ja"])
    return ui_choices(kind)[0]


def form_markdown(kind: str, heading: str) -> str:
    """Colab #@markdown bullets: each option plus when to pick it."""
    lines = [f"#@markdown **{heading}**"]
    for spec in _registry(kind).values():
        choice = spec.get("choice_ja") or spec["label_ja"]
        when = spec.get("when_ja") or spec.get("hint_ja")
        lines.append(f"#@markdown - **{choice}** … {when}")
    return "\n".join(lines)


def form_readme(kind: str) -> str:
    """Markdown bullets for the notebook intro / README (no #@markdown prefix)."""
    lines = []
    for spec in _registry(kind).values():
        choice = spec.get("choice_ja") or spec["label_ja"]
        when = spec.get("when_ja") or spec.get("hint_ja")
        lines.append(f"- **{choice}** … {when}")
    return "\n".join(lines)


def describe_run(
    *,
    connect: str = "",
    camera: str = "",
    preset: str = "",
    combat: str = "",
    story: str = "",
    invite_pose: str = "",
    toilet: str = "",
    appear: str | dict[str, Any] | None = None,
    episode: str = "",
) -> str:
    """One short Japanese block at run start: what was chosen and when to pick something else."""
    c_key = canonical_connect(connect) or DEFAULT_CONNECT
    cam_key = canonical_camera(camera) or DEFAULT_CAMERA_PACK
    p_key = canonical_preset(preset) or "balance"
    f_key = canonical_combat(combat) or "off"
    s_key = canonical_story(story) or "accept"
    pose_key = canonical_invite_pose(invite_pose) or "all_fours"
    t_key = canonical_toilet(toilet) or "off"
    shown = parse_appear(appear)
    c = CONNECT_MODES.get(c_key) or CONNECT_MODES[DEFAULT_CONNECT]
    cam = CAMERA_PACKS.get(cam_key) or CAMERA_PACKS[DEFAULT_CAMERA_PACK]
    p = PRESET_CANON.get(p_key) or PRESET_CANON["balance"]
    f = COMBAT_MODES.get(f_key) or COMBAT_MODES["off"]
    s = STORY_MODES.get(s_key) or STORY_MODES["accept"]
    pose = INVITE_POSE_MODES.get(pose_key) or INVITE_POSE_MODES["all_fours"]
    t = TOILET_MODES.get(t_key) or TOILET_MODES["off"]
    appear_ja = " ".join(("○" if shown[name] else "×") + name for name in HOSPITAL_ENCOUNTERS)
    head = f"一発 {episode}".strip() if episode else "一発"
    return (
        f"{head}\n"
        f"  1 つなぎ  {c['choice_ja']}  — {c['when_ja']}\n"
        f"  2 カメラ  {cam['choice_ja']}  — {cam['when_ja']}\n"
        f"  3 画質    {p['choice_ja']}  — {p['when_ja']}\n"
        f"  4 格闘    {f['choice_ja']}  — {f['when_ja']}\n"
        f"  5 構成    {s['choice_ja']}  — {s['when_ja']}\n"
        f"  6 誘う    {pose['choice_ja']}  — {pose['when_ja']}\n"
        f"  7 トイレ  {t['choice_ja']}  — {t['when_ja']}\n"
        f"  登場      {appear_ja}\n"
        "迷ったらこの5つの既定のままで Run all。6・7・登場は病棟だけ。"
    )
