"""Additive registries for H3 episode trailers.

Stories stay as `minimaxh3/episodes/<slug>/episode.json`. Do not edit this file
to add a plot. Copy `_template` (or an adult pack) and change the JSON.

Add a camera here: one key + lock + angles.
Add a speed/quality tradeoff here: one key + LoRA stack + steps + sampler.
Add a connect mode here: one key + how GPU beats are wired (T2V cut / prev-last
I2V / authored landing still).

Cinema LoRA is not a preset (heavy, slow). Combat is never a preset; fight
beats opt in with extra_loras: ["combat"].

Colab shows `choice_ja` in the dropdown. `when_ja` is the one-line "pick this when".
`label_ja` is the short name printed at run start. Keep those three in this file so
the form cannot drift from the engine.
"""

from __future__ import annotations

from typing import Any

# Default when a T2V episode omits render.camera_pack.
DEFAULT_CAMERA_PACK = "side2d"
DEFAULT_CONNECT = "t2v"

# Positive phrasing only. Named "slow motion" (even negated) still gets drawn.
CAMERA_PACKS: dict[str, dict[str, Any]] = {
    "side2d": {
        "label_ja": "横スク",
        "choice_ja": "横スク（真横・全身・迷ったらこれ）",
        "when_ja": "常に真横の 2D 横スクロール",
        "hint_ja": "迷ったらこれ。常に真横・全身・2D横スクロール。",
        "recommend": True,
        "lock": (
            "Locked side-on 2D side-scroller third-person gameplay camera at hip-to-shoulder height. "
            "PROFILE view: the floor runs LEFT to RIGHT across the frame. The lit doorway sits at the RIGHT edge of the frame. "
            "Adults move LEFT or RIGHT. Both adults stay full body including feet. The camera stays in the side plane and tracks "
            "only left and right on a straight line at brisk walking game speed"
        ),
        # Sex / toilet holds must not inherit the walk-track + doorway bait (it spawns giant women).
        "planted_lock": (
            "Locked side-on 2D side-scroller third-person gameplay camera at hip-to-shoulder height. "
            "PROFILE view: the floor runs LEFT to RIGHT across the frame. "
            "Adults stay on this same floor spot at normal adult human height, same scale as a standing adult woman. "
            "Hip, hand, and mouth motion stay on this floor mark. A hip thrust is in place, not a step. "
            "Nobody is giant. Nobody fills a doorway. Nobody walks. Nobody relocates. "
            "The camera HOLDS. No track, no pan, no scroll. Both adults stay full body including feet"
        ),
        "angles": (
            "locked side-on PROFILE wide at hip height, floor LEFT to RIGHT, doorway at the RIGHT edge, both adults full body including feet, horizontal track only",
            "locked side-on PROFILE at shoulder height, a half-step closer, floor LEFT to RIGHT, doorway at the RIGHT edge, both adults full body including feet, same side plane",
            "locked side-on PROFILE further back so more floor shows, hip height, floor LEFT to RIGHT, doorway at the RIGHT edge, both adults full body including feet, horizontal track only",
            "locked side-on PROFILE at desk height, both adults full body, floor LEFT to RIGHT, doorway at the RIGHT edge, same side plane, slight horizontal track",
            "locked side-on PROFILE wide at chest height, both adults full body including feet, floor LEFT to RIGHT, doorway at the RIGHT edge, camera holds then tracks left and right",
        ),
    },
    "action3d": {
        "label_ja": "3Dアクション",
        "choice_ja": "3Dアクション（引きの三人称）",
        "when_ja": "引きの三人称。カットつなぎのとき画角が回る",
        "hint_ja": "引きの三人称。カットつなぎのときショットごとに回る。",
        "lock": (
            "Pulled-back third-person 3D-action gameplay camera. Both adults stay full body including feet. "
            "The camera stays behind or beside the player at hip-to-shoulder height at brisk walking game speed"
        ),
        "angles": (
            "behind-left three-quarter at shoulder height, pulled back, both adults full body including feet",
            "behind-right three-quarter at hip height, pulled back, both adults full body including feet",
            "high three-quarter over the aisle, pulled back, both adults full body including feet",
            "low three-quarter at hip height tracking the lead adult, both adults full body including feet",
            "side-rear three-quarter at shoulder height, pulled back, both adults full body including feet",
        ),
    },
}

# t2v = every GPU beat is T2V including the first (prompt can correct; cameras may change).
# chain = first GPU beat T2V, beat 2+ I2V from the previous clip's last frame.
# landing = beat 2+ I2V onto an authored still as Picture 2 (needs stills/).
CONNECT_MODES: dict[str, dict[str, Any]] = {
    "t2v": {
        "label_ja": "カット",
        "choice_ja": "カット（本ごと独立・迷ったらこれ）",
        "when_ja": "1本目から全部 T2V。プロンプトで直したい。カメラも変えられる",
        "hint_ja": "迷ったらこれ。1本目も T2V。本ごとに撮り直し可。カメラを変えられる。",
        "recommend": True,
        "rotate_camera": True,
    },
    "chain": {
        "label_ja": "前の最終フレームから",
        "choice_ja": "前の最終フレームから続ける",
        "when_ja": "1本目は T2V。2本目以降を前クリップの最後のコマから I2V。つながり優先",
        "hint_ja": "1本目は T2V。2本目以降は前クリップの最終フレームから I2V。つながり優先。",
        "rotate_camera": False,
    },
    "landing": {
        "label_ja": "用意した最終フレームへ",
        "choice_ja": "用意した最終フレームへ着く",
        "when_ja": "stills の jpg を最後のコマにする。jpg がある話だけ",
        "hint_ja": "用意した jpg を最後のコマにする I2V。スチールがある本だけ。",
        "rotate_camera": False,
    },
}

# Scene-end walks (connect: "end" in JSON). Default keeps the vanish cut.
END_CONNECT_MODES: dict[str, dict[str, Any]] = {
    "t2v": {
        "label_ja": "カット",
        "choice_ja": "シーン終わりはカット（迷ったらこれ）",
        "when_ja": "歩きは T2V。次のシーンは独立。相手と竿が残らない",
        "hint_ja": "迷ったらこれ。行為のあとの歩きは撮り直し。次のシーンへ影響を残さない",
        "recommend": True,
    },
    "chain": {
        "label_ja": "次へ続ける",
        "choice_ja": "次のシーンへ続ける",
        "when_ja": "歩きと次の出会いを前クリップの最終フレームから I2V。相手が退場する歩きは頼んでもカットになる",
        "hint_ja": "連続して次のシーンを出すとき。相手が消える歩きは最終フレームに相手が写っているのでカットに落ちる",
    },
    "follow": {
        "label_ja": "1番に従う",
        "choice_ja": "1番のつなぎに従う",
        "when_ja": "シーン終わりも 1番どおり。1番がチェーンなら歩きもチェーン",
        "hint_ja": "1番のつなぎを歩きにも使う",
    },
}

# User-facing names. Aliases keep older episode.json valid.
# stack entries are (lora_key, strength, optional). Larry never stacks with LightX2V turbo.
PRESET_CANON: dict[str, dict[str, Any]] = {
    "speed": {
        "label_ja": "スピード",
        "choice_ja": "スピード（最速）",
        "when_ja": "試し打ち。turbo 4step。格闘 LoRA なし",
        "hint_ja": "最速。turbo 4step。格闘 LoRA は積まない。",
        "stack": [("turbo4", 1.0, False)],
        "steps": 4,
        "trigger": "",
        "sampler": "euler",
        "scheduler": "simple",
    },
    "balance": {
        "label_ja": "バランス",
        "choice_ja": "バランス（迷ったらこれ）",
        "when_ja": "普段使い。この UNet では LoRA なし euler 8",
        "hint_ja": "迷ったらこれ。LoRA なし euler 8。Larry は積まない。",
        "recommend": True,
        "stack": [("larry", 1.0, False)],
        "steps": 8,
        "trigger": "",
        "sampler": "euler",
        "scheduler": "simple",
    },
    "quality": {
        "label_ja": "質",
        "choice_ja": "質（きれい・時間かかる）",
        "when_ja": "きれい優先。この UNet では LoRA なし euler 12",
        "hint_ja": "きれい優先。LoRA なし euler 12。時間はかかる。",
        "stack": [("larry", 1.0, False)],
        "steps": 12,
        "trigger": "",
        "sampler": "euler",
        "scheduler": "beta",
    },
}


def _label_aliases(registry: dict[str, dict[str, Any]], extra: dict[str, str]) -> dict[str, str]:
    """Map short names, dropdown strings, and leftover English onto canonical keys."""
    out = dict(extra)
    for key, spec in registry.items():
        for name in (spec.get("label_ja"), spec.get("choice_ja")):
            text = str(name or "").strip()
            if text:
                out[text] = key
    return out


CAMERA_ALIASES: dict[str, str] = _label_aliases(
    CAMERA_PACKS,
    {
        "2D横スク": "side2d",
        "サイド": "side2d",
        "2d": "side2d",
        "side-scroll": "side2d",
        "3d": "action3d",
        "action": "action3d",
    },
)

CONNECT_ALIASES: dict[str, str] = _label_aliases(
    CONNECT_MODES,
    {
        "cut": "t2v",
        "t2v_cut": "t2v",
        "独立": "t2v",
        "i2v_chain": "chain",
        "last-frame": "chain",
        "prev-last": "chain",
        "連鎖": "chain",
        "前の尻から続ける": "chain",
        "最終フレームi2v": "chain",
        "i2v_landing": "landing",
        "still_as_last": "landing",
        "landing-still": "landing",
        "着地": "landing",
        "着地スチールへ着く": "landing",
        "最終フレーム用意": "landing",
    },
)

END_CONNECT_ALIASES: dict[str, str] = _label_aliases(
    END_CONNECT_MODES,
    {
        "cut": "t2v",
        "独立": "t2v",
        "続ける": "chain",
        "連続": "chain",
        "inherit": "follow",
        "従う": "follow",
    },
)

# Combat V2 is optional. Default off. On = High-Memory only (VRAM 70+ or RAM 60+).
COMBAT_MODES: dict[str, dict[str, Any]] = {
    "off": {
        "label_ja": "オフ",
        "choice_ja": "格闘LoRAオフ（迷ったらこれ）",
        "when_ja": "行為ルート。戦いなし。後背位とベロチュー。A100 40GB はこれ",
        "hint_ja": "迷ったらこれ。話は行為。Combat は積まない。",
        "recommend": True,
    },
    "on": {
        "label_ja": "オン",
        "choice_ja": "格闘LoRAオン（ハイメモリ専用）",
        "when_ja": "戦いルート。06と10が横スク。話も切り替わる。ハイメモリ専用",
        "hint_ja": "ハイメモリ専用。話は戦い。06と10に Combat。足りないと LoRA だけ落ちる。",
    },
}

COMBAT_ALIASES: dict[str, str] = _label_aliases(
    COMBAT_MODES,
    {
        "combat": "on",
        "combat_on": "on",
        "highmem": "on",
        "ハイメモリ": "on",
        "なし": "off",
        "しない": "off",
        "no-combat": "off",
    },
)

# Hospital-exit story pack. Body JSON is ○受け入れる. Other futures are on_* overlays.
# Kasumi has no on_* keys; this dropdown is ignored there.
STORY_MODES: dict[str, dict[str, Any]] = {
    "accept": {
        "label_ja": "受け入れる",
        "choice_ja": "○受け入れる（生存・完了・迷ったらこれ）",
        "when_ja": "戸惑いながら身体を張って出口へ。ミッション完了",
        "hint_ja": "迷ったらこれ。生存セックス。接合のまま出口。Combat なし",
        "recommend": True,
        "combat": "off",
        "complete": True,
        "menu_selected": 1,
    },
    "invite": {
        "label_ja": "誘う",
        "choice_ja": "□誘う（淫欲・失敗）",
        "when_ja": "こちらから攻める濃厚セックス。院内で淫欲に呑まれて失敗",
        "hint_ja": "ノリノリ。各シーンのあと次へ行ける。最後だけ失敗。Combat なし",
        "combat": "off",
        "complete": False,
        "fail_reason": "淫欲に呑まれた",
        "menu_selected": 2,
    },
    "evade": {
        "label_ja": "回避",
        "choice_ja": "×回避（出口・完了）",
        "when_ja": "エロを避けて一人で出口。ミッション完了",
        "hint_ja": "行為なし。すり抜け。Combat なし",
        "combat": "off",
        "complete": True,
        "menu_selected": 3,
    },
    "fight_win": {
        "label_ja": "戦って勝つ",
        "choice_ja": "△戦って勝つ（完了・ハイメモリ）",
        "when_ja": "れいを倒して出口。みきは回避。かなはすり抜け。しのを倒す。ハイメモリ",
        "hint_ja": "06と10に Combat。しのを倒す。敗北Hなし",
        "combat": "on",
        "complete": True,
        "menu_selected": 0,
    },
    "fight_lose": {
        "label_ja": "戦って負ける",
        "choice_ja": "△戦って負ける（敗北H・失敗・ハイメモリ）",
        "when_ja": "しのに倒されて専用敗北H。ミッション失敗。ハイメモリ",
        "hint_ja": "10でしのに敗北。12が敗北H。出られない",
        "combat": "on",
        "complete": False,
        "fail_reason": "感染者に倒された",
        "menu_selected": 0,
    },
}

STORY_OVERLAY_KEYS: dict[str, str] = {
    "accept": "on_accept",
    "invite": "on_invite",
    "evade": "on_evade",
    "fight_win": "on_fight_win",
    "fight_lose": "on_fight_lose",
}

STORY_ALIASES: dict[str, str] = _label_aliases(
    STORY_MODES,
    {
        "受け入れる": "accept",
        "誘う": "invite",
        "回避": "evade",
        "戦う": "fight_win",
        "勝ち": "fight_win",
        "負け": "fight_lose",
        "敗北": "fight_lose",
        "敗北H": "fight_lose",
        "survival": "accept",
        "lust": "invite",
        "escape": "evade",
        "win": "fight_win",
        "lose": "fight_lose",
    },
)


# Invite pose (hospital □誘う only). Kasumi has no invite_pose_* keys; ignored there.
INVITE_POSE_MODES: dict[str, dict[str, Any]] = {
    "all_fours": {
        "label_ja": "四つん這い",
        "choice_ja": "四つん這い股広げ（迷ったらこれ）",
        "when_ja": "四つん這いで誘う。挿入前→挿入根元→パコ中出し→輪が狭まる→歩きの5本",
        "hint_ja": "迷ったらこれ。あやが四つん這いで股を広げる。終わりはあや一人歩き",
        "recommend": True,
    },
    "m_open": {
        "label_ja": "M字",
        "choice_ja": "M字開脚仰向け",
        "when_ja": "仰向けM字。根元まで入れてからパコ中出し→歩きの3本",
        "hint_ja": "あやが仰向けM字。先に根本まで入れてからパコ。終わりはあや一人歩き",
    },
    "ride": {
        "label_ja": "騎乗位",
        "choice_ja": "騎乗・足を揃えて立ってから下ろす",
        "when_ja": "出会いでベロチュー。行為は口→細い柱の対面騎乗→中出し→歩きの4本。跪きから一度まっすぐ立ち、それから膝を曲げて下ろす",
        "hint_ja": "竿役は仰向け。あやは足を肋骨のすぐ横に揃えて立つ。それから膝を曲げ、あやの手が竿役の胸。終わりはあや一人歩き",
    },
    "ride_bent": {
        "label_ja": "騎乗・最初から膝曲げ",
        "choice_ja": "騎乗・最初から膝を曲げて下ろす",
        "when_ja": "出会いでベロチュー。行為は口→両膝を曲げたままの対面騎乗→中出し→歩きの4本",
        "hint_ja": "竿役は仰向け。あやは最初から両膝を曲げ、足裏を肋骨の左右に置く。相手の手が胸。一度下ろして根元。終わりはあや一人歩き",
    },
    "stand": {
        "label_ja": "立ちバック",
        "choice_ja": "壁立ちバック",
        "when_ja": "壁に右腕、左手で尻を開いて振り返る。先を当てる→肛門へ根元→パコ中出し→抜いて輪が狭まる→歩きの5本",
        "hint_ja": "あやが壁に右腕。左手で尻を開く。肛門が画面中央。終わりはあや一人歩き",
    },
    "nelson": {
        "label_ja": "フルネルソン",
        "choice_ja": "フルネルソンアナル",
        "when_ja": "あやが正面。竿役は背後。両脚を抱えて肛門だけ。顔と体は入れ替えない",
        "hint_ja": "あやの顔が正面。竿役の顔はあやの頭の後ろ。竿は肛門だけ。終わりはあや一人歩き",
    },
    "sit": {
        "label_ja": "対面座位",
        "choice_ja": "対面座位",
        "when_ja": "竿役が床に座る。あやが対面で跨り、一回の押しで根元まで。終わりはあや一人歩き",
        "hint_ja": "竿役は座って竿を真上。あやは胸に手を置いて腰を下ろす",
    },
    "embrace": {
        "label_ja": "抱擁",
        "choice_ja": "抱擁ベロチュー→壁片足→クンニ→両足抱え",
        "when_ja": "spotの次から。抱きついて背中に手を回しベロチュー。壁に背、片足は床。しゃがんでクンニ。両足を抱える。犬・スライム・獣・ギンは除く",
        "hint_ja": "角だけ背後ハグから振り向きベロチュー。キスLoRA必須",
    },
    "jacko": {
        "label_ja": "後ろアナル",
        "choice_ja": "後ろアナル",
        "when_ja": "顔と胸が床、腰は高い、両脚は左右。竿役が腰の上。尻がカメラ。竿は上から肛門。今の行為は残す",
        "hint_ja": "あやが受け。set は未挿入の cut。behind も未挿入。anal で一度下ろして根元。中出し、開き、口",
    },
}

INVITE_POSE_OVERLAY_KEYS: dict[str, str] = {
    "all_fours": "invite_pose_all_fours",
    "m_open": "invite_pose_m_open",
    "ride": "invite_pose_ride",
    "ride_bent": "invite_pose_ride",
    "stand": "invite_pose_stand",
    "nelson": "invite_pose_nelson",
    "sit": "invite_pose_sit",
    "embrace": "invite_pose_embrace",
    "jacko": "invite_pose_jacko",
}

INVITE_POSE_ALIASES: dict[str, str] = _label_aliases(
    INVITE_POSE_MODES,
    {
        "四つん這い": "all_fours",
        "四つん這い股広げ": "all_fours",
        "all-fours": "all_fours",
        "doggy": "all_fours",
        "M字": "m_open",
        "M字開脚": "m_open",
        "m字": "m_open",
        "missionary": "m_open",
        "騎乗位": "ride",
        "細い柱": "ride",
        "対面M字騎乗（口のあと）": "ride",
        "騎乗・足を揃えて立ってから下ろす": "ride",
        "cowgirl": "ride",
        "曲げ膝": "ride_bent",
        "騎乗・曲げ膝": "ride_bent",
        "騎乗・曲げ膝（口のあと）": "ride_bent",
        "騎乗・最初から膝を曲げて下ろす": "ride_bent",
        "jupo": "ride",
        "ベロチュー→じゅぼ→騎乗位": "ride",
        "壁立ちバック": "stand",
        "立ちバック": "stand",
        "フルネルソン": "nelson",
        "フルネルソンアナル": "nelson",
        "対面座位": "sit",
        "座位": "sit",
        "抱擁": "embrace",
        "抱擁ベロチュー": "embrace",
        "両足抱え": "embrace",
        "後ろアナル": "jacko",
    },
)

# Optional toilet between みき and れい. Any choice continues to the next scene.
TOILET_MODES: dict[str, dict[str, Any]] = {
    "off": {
        "label_ja": "行かない",
        "choice_ja": "トイレに行かない（迷ったらこれ）",
        "when_ja": "道中は廊下のまま。次はれい",
        "hint_ja": "迷ったらこれ。04はれいの登場",
        "recommend": True,
    },
    "pee": {
        "label_ja": "小便",
        "choice_ja": "トイレ・小便",
        "when_ja": "洋式汚物まみれ。座って小便。触手はこの便器に出ない",
        "hint_ja": "汚れた白い洋式に座る→小便→立つ。触手は有機物便器だけ",
    },
    "masturbate": {
        "label_ja": "オナニー",
        "choice_ja": "トイレ・オナニー",
        "when_ja": "洋式汚物まみれ。座って手でオナニー。触手はこの便器に出ない",
        "hint_ja": "汚れた白い洋式に座る→手でオナニー→立つ",
    },
    "tentacle": {
        "label_ja": "触手",
        "choice_ja": "トイレ・触手",
        "when_ja": "有機物植物の洋式便器。粘液まみれ。触手はこの便器だけ",
        "hint_ja": "植物の洋式に座って触手。洋式汚物と和式汚物には触手を出さない",
    },
    "finger": {
        "label_ja": "ディルド",
        "choice_ja": "トイレ・ディルド",
        "when_ja": "洋式汚物まみれ。座る→緑の細長いディルドを持つ→膣へ出し入れ→絶頂→抜く。触手はこの便器に出ない",
        "hint_ja": "汚れた白い洋式にカメラ向きで座り、脚を開く。右手で緑のディルドを膣へ出し入れ",
    },
    "wash": {
        "label_ja": "和式排出",
        "choice_ja": "トイレ・和式排出",
        "when_ja": "和式汚物まみれ。しゃがんで排出。触手はこの便器に出ない",
        "hint_ja": "汚れた和式にしゃがむ→排出→立つ。洋式便座は出さない",
    },
    "wash_miki": {
        "label_ja": "和式ミキ",
        "choice_ja": "トイレ・和式ミキ",
        "when_ja": "和式汚物まみれ。ミキが後ろから入る。触手はこの便器に出ない",
        "hint_ja": "汚れた和式。しゃがみのあとミキ→根元→中→キスして歩く",
    },
}

TOILET_OVERLAY_KEYS: dict[str, str] = {
    "pee": "on_toilet_pee",
    "masturbate": "on_toilet_masturbate",
    "tentacle": "on_toilet_tentacle",
    "finger": "on_toilet_finger",
    "wash": "on_toilet_wash",
    "wash_miki": "on_toilet_wash_miki",
}

TOILET_ALIASES: dict[str, str] = _label_aliases(
    TOILET_MODES,
    {
        "行かない": "off",
        "なし": "off",
        "skip": "off",
        "小便": "pee",
        "おしっこ": "pee",
        "pee": "pee",
        "オナニー": "masturbate",
        "onanii": "masturbate",
        "触手": "tentacle",
        "tentacles": "tentacle",
        "アナル指": "finger",
        "トイレ・アナル指": "finger",
        "指": "finger",
        "finger": "finger",
        "和式": "wash",
        "和式排出": "wash",
        "wash": "wash",
        "squat pan": "wash",
        "和式ミキ": "wash_miki",
        "wash miki": "wash_miki",
        "squat miki": "wash_miki",
    },
)

# Optional ashen infected (Colab 8). Default off. Not in appear-all.
GIN_MODES: dict[str, dict[str, Any]] = {
    "off": {
        "label_ja": "出ない",
        "choice_ja": "灰色・出ない（迷ったらこれ）",
        "when_ja": "灰色の長い舌は出さない",
        "hint_ja": "迷ったらこれ。追加イベントなし",
        "recommend": True,
    },
    "taken": {
        "label_ja": "犯される",
        "choice_ja": "灰色・騎乗・最初から膝曲げ",
        "when_ja": "長い舌がクリを24cmに。口のあと、両膝を曲げたままギンが跨ぐ。終わりは竿も相手も消えてあや一人歩き",
        "hint_ja": "あやが24cmを生やされて跨がれる。両膝は最初から曲がったまま。ギンの手があやの胸。終わりは完全消滅",
    },
    "taken_column": {
        "label_ja": "犯される・細い柱",
        "choice_ja": "灰色・騎乗・足を揃えて立つ",
        "when_ja": "長い舌がクリを24cmに。口のあと、ギンが一度まっすぐ立ってから膝を曲げて騎乗。終わりは竿も相手も消えてあや一人歩き",
        "hint_ja": "ギンが細い柱で跨ぎ、手をあやの胸へ置いて一度下ろす。終わりは完全消滅",
    },
    "fuck": {
        "label_ja": "犯す",
        "choice_ja": "灰色・犯す（正常位）",
        "when_ja": "長い舌がクリを24cmに。あやが正常位で犯す。終わりは竿も相手も消えてあや一人歩き",
        "hint_ja": "あやが24cmで正常位。根元まで入れてからパコ。終わりは完全消滅",
    },
    "invite_doggy": {
        "label_ja": "誘う後背",
        "choice_ja": "灰色・誘う後背",
        "when_ja": "長い舌がクリを24cmに。四つん這いで誘われて後ろから。終わりは竿も相手も消えてあや一人歩き",
        "hint_ja": "我慢できない顔で後ろから。終わりは完全消滅",
    },
    "jacko": {
        "label_ja": "後ろアナル",
        "choice_ja": "灰色・後ろアナル",
        "when_ja": "ギンが受け。顔と胸が床、腰は高い。あやの grown erect 24cm が上から肛門。犯す枝は残す",
        "hint_ja": "尻がカメラ。set と behind は未挿入。anal で根元。中出し、開き、口。犯すは別",
    },
}

GIN_OVERLAY_KEYS: dict[str, str] = {
    "taken": "on_gin_taken",
    "taken_column": "on_gin_taken",
    "fuck": "on_gin_fuck",
    "invite_doggy": "on_gin_invite_doggy",
    "jacko": "on_gin_jacko",
}

GIN_ALIASES: dict[str, str] = _label_aliases(
    GIN_MODES,
    {
        "出ない": "off",
        "なし": "off",
        "skip": "off",
        "犯される": "taken",
        "騎乗": "taken",
        "灰色・犯される（騎乗）": "taken",
        "灰色・騎乗・細い柱": "taken_column",
        "灰色・騎乗・足を揃えて立つ": "taken_column",
        "犯す": "fuck",
        "正常位": "fuck",
        "誘う後背": "invite_doggy",
        "後背": "invite_doggy",
        "灰色・後ろアナル": "jacko",
        "後ろアナル": "jacko",
    },
)

# Optional horned infected (Colab 9). Default off. Standing joins stay. Ride and stall are separate stories.
TSUNO_MODES: dict[str, dict[str, Any]] = {
    "off": {
        "label_ja": "出ない",
        "choice_ja": "角・出ない（迷ったらこれ）",
        "when_ja": "角の頭は出さない",
        "hint_ja": "迷ったらこれ。追加イベントなし",
        "recommend": True,
    },
    "accept_stand": {
        "label_ja": "受け入れる立ちバック",
        "choice_ja": "角・受け入れる立ちバック",
        "when_ja": "壁に手をついて立ちバックだけ。終わりは相手が消えてあや一人歩き",
        "hint_ja": "あやが壁に手。24cm灰色の竿。立ちバックのみ",
    },
    "invite_stand": {
        "label_ja": "誘う立ちバック",
        "choice_ja": "角・誘う立ちバック",
        "when_ja": "壁の挿入の前に、抱きながら肛門へ入れる拍が残る。in と peak は誘うの壁立ちバックと同じ。終わりは相手が消えてあや一人歩き",
        "hint_ja": "横から肛門。壁に両手。終わりはあや一人",
    },
    "anal_back": {
        "label_ja": "後ろアナル",
        "choice_ja": "角・後ろアナル（結合部が見える）",
        "when_ja": "四つん這いの前に、壁で胸を掴んで入れる拍が残る。in と peak は四つん這い股広げと同じ。肛門。終わりは相手が消えてあや一人歩き",
        "hint_ja": "胸と頬が床。膝は開く。竿は肛門。終わりはあや一人",
    },
    "nelson": {
        "label_ja": "フルネルソンアナル",
        "choice_ja": "角・フルネルソンアナル",
        "when_ja": "胸を掴んだ密着から、両脚を抱えてアナルだけ。膣には入れない",
        "hint_ja": "胸を鷲掴み。入れたまま両脚を抱える。竿は肛門だけ",
    },
    "invite_ride": {
        "label_ja": "病室で横になって挿入",
        "choice_ja": "角・病室で横になって挿入",
        "when_ja": "廃病室。座り、キス、しゃがみ口、顔射、横になって一度入れて HOLD、円腰の中出し、キス、入り口のあや一人",
        "hint_ja": "角はベッドの縁に座る。個室へ行かない。終わりはあや一人",
    },
    "invite_ride_column": {
        "label_ja": "病室で横になって挿入と同じ",
        "choice_ja": "角・騎乗・細い柱",
        "when_ja": "角・病室で横になって挿入と同じ並び。一覧には出さない",
        "hint_ja": "同じ寝室の並び",
        "form": False,
    },
    "invite_jacko": {
        "label_ja": "病室でベッドの後ろアナル",
        "choice_ja": "角・病室でベッドの後ろアナル",
        "when_ja": "顔射のあと別枝。寝室のまま後ろから肛門。個室へ行かない。終わりはあや一人",
        "hint_ja": "病室のベッド。胸と頬がマット。一度入れて根元。中出し、開き、口、歩き",
    },
    "wash_carry": {
        "label_ja": "個室",
        "choice_ja": "角・個室",
        "when_ja": "新話。通路で抱えて個室のアナル。終わりはあや一人。トイレ枠は消さない",
        "hint_ja": "お姫様抱っこから個室。04-toilet はコピーしない",
    },
}

TSUNO_OVERLAY_KEYS: dict[str, str] = {
    "accept_stand": "on_tsuno_accept_stand",
    "invite_stand": "on_tsuno_invite_stand",
    "anal_back": "on_tsuno_anal_back",
    "nelson": "on_tsuno_nelson",
    "invite_ride": "on_tsuno_invite_ride",
    "invite_ride_column": "on_tsuno_invite_ride",
    "invite_jacko": "on_tsuno_invite_jacko",
    "wash_carry": "on_tsuno_wash_carry",
}

TSUNO_ALIASES: dict[str, str] = _label_aliases(
    TSUNO_MODES,
    {
        "出ない": "off",
        "なし": "off",
        "skip": "off",
        "受け入れる": "accept_stand",
        "受け入れる立ちバック": "accept_stand",
        "立ちバック": "accept_stand",
        "誘う": "invite_stand",
        "誘う立ちバック": "invite_stand",
        "後ろアナル": "anal_back",
        "結合部": "anal_back",
        "アナル": "anal_back",
        "フルネルソン": "nelson",
        "フルネルソンアナル": "nelson",
        "角・騎乗": "invite_ride",
        "騎乗": "invite_ride",
        "角・騎乗・細い柱": "invite_ride_column",
        "角・寝室アナル": "invite_jacko",
        "寝室アナル": "invite_jacko",
        "角・病室で横になって挿入": "invite_ride",
        "角・病室でベッドの後ろアナル": "invite_jacko",
        "角・個室": "wash_carry",
        "個室": "wash_carry",
        "個室アナル": "wash_carry",
    },
)

# Optional quadruped (Colab 10). Default off. Not in appear-all. May stack with gin/tsuno/species.
DOG_MODES: dict[str, dict[str, Any]] = {
    "off": {
        "label_ja": "出ない",
        "choice_ja": "犬・出ない（迷ったらこれ）",
        "when_ja": "四つ足は出さない",
        "hint_ja": "迷ったらこれ。追加イベントなし",
        "recommend": True,
    },
    "evade": {
        "label_ja": "回避",
        "choice_ja": "犬・回避",
        "when_ja": "右から飛び込んだ四つ足を残して、あやが左へ走る。終わりはあや一人歩き",
        "hint_ja": "あやは左へ。四つ足は右に残る",
    },
    "accept": {
        "label_ja": "受け入れる",
        "choice_ja": "犬・受け入れる",
        "when_ja": "右の壁で後脚立ち。24cmがマンコへ。終わりはあや一人歩き",
        "hint_ja": "手は壁。足は床。短い突きのあと WHITE goo",
    },
    "invite_rear": {
        "label_ja": "誘う伏せ",
        "choice_ja": "犬・誘う伏せ",
        "when_ja": "その場で仰向けに開いて舌、それから背中へ。終わりはあや一人歩き",
        "hint_ja": "舌のあと伏せ。24cmは根元まで。抜けない",
    },
    "invite_oral": {
        "label_ja": "誘う口",
        "choice_ja": "犬・誘う口",
        "when_ja": "舌のあと口。平らな床で仰向け。終わりはあや一人歩き",
        "hint_ja": "口から溢れて、抜いて見せて、胴を抱える",
    },
}

DOG_OVERLAY_KEYS: dict[str, str] = {
    "evade": "on_dog_evade",
    "accept": "on_dog_accept",
    "invite_rear": "on_dog_invite_rear",
    "invite_oral": "on_dog_invite_oral",
}

DOG_ALIASES: dict[str, str] = _label_aliases(
    DOG_MODES,
    {
        "出ない": "off",
        "なし": "off",
        "skip": "off",
        "回避": "evade",
        "受け入れる": "accept",
        "誘う伏せ": "invite_rear",
        "伏せ": "invite_rear",
        "誘う口": "invite_oral",
        "口": "invite_oral",
    },
)

# Optional non-human partner (Colab 11). Slime and anthro are one dropdown, so they never both expand.
SPECIES_MODES: dict[str, dict[str, Any]] = {
    "off": {
        "label_ja": "出ない",
        "choice_ja": "異種・出ない（迷ったらこれ）",
        "when_ja": "スライムもケモノも出さない",
        "hint_ja": "迷ったらこれ。追加イベントなし",
        "recommend": True,
    },
    "slime": {
        "label_ja": "スライム",
        "choice_ja": "異種・スライム",
        "when_ja": "左から真後ろ。密着したまま24cmがマンコへ。ケモノは出ない",
        "hint_ja": "スライムだけ。ケモノとは同時に出さない",
    },
    "anthro": {
        "label_ja": "ケモノ",
        "choice_ja": "異種・ケモノ",
        "when_ja": "左から真後ろの二足。密着したまま24cmがマンコへ。スライムは出ない",
        "hint_ja": "ケモノだけ。スライムとは同時に出さない",
    },
}

SPECIES_OVERLAY_KEYS: dict[str, str] = {
    "slime": "on_species_slime",
    "anthro": "on_species_anthro",
}

SPECIES_ALIASES: dict[str, str] = _label_aliases(
    SPECIES_MODES,
    {
        "出ない": "off",
        "なし": "off",
        "skip": "off",
        "スライム": "slime",
        "ケモノ": "anthro",
        "獣": "anthro",
    },
)

# Futanari Rei escape (dedicated Colab). Keys are rei_* so hospital toilet/invite never fire.
REI_MAST_MODES: dict[str, dict[str, Any]] = {
    "skip": {
        "label_ja": "しない",
        "choice_ja": "合間おな・しない（迷ったらこれ）",
        "when_ja": "S03/S07/S11/S15 を全部スキップして走る",
        "hint_ja": "迷ったらこれ。合間オナニーなし",
        "recommend": True,
    },
    "stand": {
        "label_ja": "立ちおな",
        "choice_ja": "合間おな・立ち",
        "when_ja": "走りの合間に立って根元から先まで擦る",
        "hint_ja": "立ち。手は根元→先。射精しても24cmは残す",
    },
    "back": {
        "label_ja": "仰向けおな",
        "choice_ja": "合間おな・仰向け",
        "when_ja": "走りの合間に床へ仰向け。床は沈まない",
        "hint_ja": "仰向け。肉床に沈まない。24cmは残す",
    },
}

REI_MAST_OVERLAY_KEYS: dict[str, str] = {
    "stand": "rei_mast_stand",
    "back": "rei_mast_back",
}

REI_MAST_ALIASES: dict[str, str] = _label_aliases(
    REI_MAST_MODES,
    {
        "しない": "skip",
        "なし": "skip",
        "off": "skip",
        "立ち": "stand",
        "立ちおな": "stand",
        "仰向け": "back",
        "仰向けおな": "back",
        "on-back": "back",
    },
)

REI_TOILET_MODES: dict[str, dict[str, Any]] = {
    "ta": {
        "label_ja": "着座おな",
        "choice_ja": "トイレ・着座おな射精（迷ったらこれ）",
        "when_ja": "肉壁の洋式形に座って射精。陶器も脱糞もなし",
        "hint_ja": "迷ったらこれ。便器は肉。汚れフラグなし",
        "recommend": True,
    },
    "tb": {
        "label_ja": "着座小便",
        "choice_ja": "トイレ・着座小便",
        "when_ja": "座って小便の筋が見える。陶器も脱糞もなし",
        "hint_ja": "肉壁便器。肌に糞を塗らない",
    },
    "tc": {
        "label_ja": "触手",
        "choice_ja": "トイレ・肉壁の触手がじゅぼ",
        "when_ja": "便器のまわりから生えた触手の円口が24cmを根元まで吞む",
        "hint_ja": "触手。人間の口にしない。脱糞なし",
    },
}

REI_TOILET_OVERLAY_KEYS: dict[str, str] = {
    "ta": "rei_toilet_ta",
    "tb": "rei_toilet_tb",
    "tc": "rei_toilet_tc",
}

REI_TOILET_ALIASES: dict[str, str] = _label_aliases(
    REI_TOILET_MODES,
    {
        "着座おな": "ta",
        "オナニー射精": "ta",
        "T-a": "ta",
        "ta": "ta",
        "着座小便": "tb",
        "小便": "tb",
        "T-b": "tb",
        "tb": "tb",
        "全身に塗る": "tc",
        "全身": "tc",
        "T-c": "tc",
        "tc": "tc",
        "触手": "tc",
        "触手フェラ": "tc",
        "tentacle": "tc",
        "オナニー": "ta",
        "小便": "tb",
        "pee": "tb",
    },
)

REI_BEAST_MODES: dict[str, dict[str, Any]] = {
    "accept": {
        "label_ja": "受け入れる",
        "choice_ja": "敵1・受け入れる（立ち・迷ったらこれ）",
        "when_ja": "立ったまま。円口が24cmを根元まで吞んで蠕動（いわゆるじゅぼ）",
        "hint_ja": "迷ったらこれ。立ち。円口は mystic のみ",
        "recommend": True,
    },
    "invite": {
        "label_ja": "誘う",
        "choice_ja": "敵1・誘う（仰向け・股開き）",
        "when_ja": "その場で仰向け、笑顔で股を開く。円口が上から吞んで蠕動",
        "hint_ja": "誘う。仰向け。人間の口にしない",
    },
    "evade": {
        "label_ja": "回避",
        "choice_ja": "敵1・回避（行為なし）",
        "when_ja": "円口の行為を飛ばしてフェード→走り",
        "hint_ja": "回避。S05なし",
    },
}

REI_BEAST_OVERLAY_KEYS: dict[str, str] = {
    "accept": "rei_beast_accept",
    "invite": "rei_beast_invite",
    # evade has no S05 cut, but S06 still needs its own wording: the maw never
    # swallowed her, so the run after it must not say "after ejaculation".
    "evade": "rei_beast_evade",
}

REI_BEAST_ALIASES: dict[str, str] = _label_aliases(
    REI_BEAST_MODES,
    {
        "受け入れる": "accept",
        "立ち": "accept",
        "standing": "accept",
        "誘う": "invite",
        "仰向け": "invite",
        "股開き": "invite",
        "回避": "evade",
        "しない": "evade",
        "skip": "evade",
    },
)

REI_MOTH_MODES: dict[str, dict[str, Any]] = {
    "tail": {
        "label_ja": "尾の第二口",
        "choice_ja": "蛾女・尾端の第二口（迷ったらこれ）",
        "when_ja": "尾先の円口が根元まで密封して蠕動。優先",
        "hint_ja": "迷ったらこれ。人間の股間に穴を移さない",
        "recommend": True,
    },
    "mouth": {
        "label_ja": "上の口",
        "choice_ja": "蛾女・上の口（唇と舌）",
        "when_ja": "人間の上半身の口。唇と舌の軌道。下半身は虫のまま",
        "hint_ja": "上の口。虫腹と多脚は残す",
    },
}

REI_MOTH_OVERLAY_KEYS: dict[str, str] = {
    "tail": "rei_moth_tail",
    "mouth": "rei_moth_mouth",
}

REI_MOTH_ALIASES: dict[str, str] = _label_aliases(
    REI_MOTH_MODES,
    {
        "尾": "tail",
        "尾の穴": "tail",
        "第二口": "tail",
        "上の口": "mouth",
        "口": "mouth",
    },
)

REI_ATTACK_MODES: dict[str, dict[str, Any]] = {
    "rei": {
        "label_ja": "レイから",
        "choice_ja": "レイから襲う（迷ったらこれ）",
        "when_ja": "レイが腰を掴んで肉壁へ押し付ける",
        "hint_ja": "迷ったらこれ。レイから",
        "recommend": True,
    },
    "her": {
        "label_ja": "サキュバスから",
        "choice_ja": "サキュバスから襲う",
        "when_ja": "サキュバスが飛びかかり羽で包む",
        "hint_ja": "サキュバスから。羽と爪は残す",
    },
}

REI_ATTACK_OVERLAY_KEYS: dict[str, str] = {
    "rei": "rei_attack_rei",
    "her": "rei_attack_her",
}

REI_ATTACK_ALIASES: dict[str, str] = _label_aliases(
    REI_ATTACK_MODES,
    {
        "レイから襲う": "rei",
        "レイから": "rei",
        "サキュバスから襲う": "her",
        "サキュバスから": "her",
    },
)

REI_KISS_MODES: dict[str, dict[str, Any]] = {
    "off": {
        "label_ja": "しない",
        "choice_ja": "キスしない（迷ったらこれ）",
        "when_ja": "顔のキスを飛ばす。フェラではない",
        "hint_ja": "迷ったらこれ。キスなし",
        "recommend": True,
    },
    "on": {
        "label_ja": "ベロチュー",
        "choice_ja": "ベロチューする",
        "when_ja": "口を開けて舌が見えるキス。羽と角は残す。フェラではない",
        "hint_ja": "顔のキス。竿は使わない",
    },
}

REI_KISS_OVERLAY_KEYS: dict[str, str] = {
    "on": "rei_kiss_on",
}

REI_KISS_ALIASES: dict[str, str] = _label_aliases(
    REI_KISS_MODES,
    {
        "しない": "off",
        "なし": "off",
        "skip": "off",
        "する": "on",
        "キス": "on",
        "ベロチュー": "on",
        "舌": "on",
    },
)

REI_ORAL_MODES: dict[str, dict[str, Any]] = {
    "skip": {
        "label_ja": "しない",
        "choice_ja": "フェラもクンニもしない（迷ったらこれ）",
        "when_ja": "口のカットを飛ばして挿入へ",
        "hint_ja": "迷ったらこれ。口なし",
        "recommend": True,
    },
    "her": {
        "label_ja": "サキュバスがフェラ",
        "choice_ja": "サキュバスがフェラ",
        "when_ja": "跪いて唇が24cmを先から根元まで往復。羽と角は残す。いわゆるフェラ",
        "hint_ja": "サキュバスがフェラ。根元まで",
    },
    "rei": {
        "label_ja": "レイがクンニ",
        "choice_ja": "レイがクンニ",
        "when_ja": "レイの舌が無毛の割れ目を下から上へ。いわゆるクンニ",
        "hint_ja": "レイがクンニ。羽と爪は残す",
    },
}

REI_ORAL_OVERLAY_KEYS: dict[str, str] = {
    "her": "rei_oral_her",
    "rei": "rei_oral_rei",
}

REI_ORAL_ALIASES: dict[str, str] = _label_aliases(
    REI_ORAL_MODES,
    {
        "しない": "skip",
        "なし": "skip",
        "off": "skip",
        "サキュバスが軸へ": "her",
        "軸へ": "her",
        "フェラ": "her",
        "サキュバスがフェラ": "her",
        "レイが裂へ": "rei",
        "裂へ": "rei",
        "クンニ": "rei",
        "レイがクンニ": "rei",
    },
)

REI_POSE_MODES: dict[str, dict[str, Any]] = {
    "fours": {
        "label_ja": "四つん這い後ろから",
        "choice_ja": "四つん這い後ろから（迷ったらこれ）",
        "when_ja": "掌と膝。後ろから根元まで入れて止めてから往復",
        "hint_ja": "迷ったらこれ。名称ではなく掌と膝と後ろから",
        "recommend": True,
    },
    "wall": {
        "label_ja": "壁に手で立つ",
        "choice_ja": "壁に手・立ったまま後ろから",
        "when_ja": "壁に掌。立ったまま根元まで入れてから往復",
        "hint_ja": "壁に掌。つのイベントとは無関係",
    },
    "straddle": {
        "label_ja": "跨がり",
        "choice_ja": "跨がり・沈めて上げ下ろし",
        "when_ja": "跨がって沈めて上げ下ろし。レイは仰向けで止める",
        "hint_ja": "跨がり。沈めて上げ下ろし",
    },
    "supine": {
        "label_ja": "仰向け膝開き",
        "choice_ja": "仰向け・膝を開いて根元まで",
        "when_ja": "相手が仰向け。根元まで入れて止めてから往復",
        "hint_ja": "仰向け。名称ではなく膝開き",
    },
}

REI_POSE_OVERLAY_KEYS: dict[str, str] = {
    "fours": "rei_pose_fours",
    "wall": "rei_pose_wall",
    "straddle": "rei_pose_straddle",
    "supine": "rei_pose_supine",
}

REI_POSE_ALIASES: dict[str, str] = _label_aliases(
    REI_POSE_MODES,
    {
        "四つん這い": "fours",
        "後ろから": "fours",
        "後背": "fours",
        "back": "fours",
        "壁に手": "wall",
        "立ち": "wall",
        "跨がり": "straddle",
        "騎乗": "straddle",
        "仰向け": "supine",
        "膝開き": "supine",
    },
)

REI_ESCAPE_OVERLAY_KEYS: tuple[str, ...] = tuple(
    {
        **REI_MAST_OVERLAY_KEYS,
        **REI_TOILET_OVERLAY_KEYS,
        **REI_BEAST_OVERLAY_KEYS,
        **REI_MOTH_OVERLAY_KEYS,
        **REI_ATTACK_OVERLAY_KEYS,
        **REI_KISS_OVERLAY_KEYS,
        **REI_ORAL_OVERLAY_KEYS,
        **REI_POSE_OVERLAY_KEYS,
    }.values()
)

REI_FILTH_SEAT = (
    "DIRTY-STATE SEAT: smeared dark-brown viscous feces on buttocks and thighs, stains remain in every later shot."
)
REI_FILTH_BODY = (
    "DIRTY-STATE BODY: body painted with thick dark-brown feces on face, breasts, belly, penis, legs. "
    "Stains transfer onto the enemy."
)
REI_FILTH_HINT: dict[str, str] = {"seat": "着座汚れ", "body": "全身汚れ"}

HOSPITAL_ENCOUNTERS: tuple[str, ...] = ("miki", "rei", "kana", "shino")
DEFAULT_APPEAR: dict[str, bool] = {name: True for name in HOSPITAL_ENCOUNTERS}
FIGHT_STORIES: frozenset[str] = frozenset({"fight_win", "fight_lose"})
ENCOUNTER_LABEL_JA: dict[str, str] = {
    "miki": "みき",
    "rei": "れい",
    "kana": "かな",
    "shino": "しの",
}

APPEAR_ALIASES: dict[str, str] = {
    "みき": "miki",
    "れい": "rei",
    "かな": "kana",
    "しの": "shino",
}

# Colab episode dropdown. Slug stays the folder name; choice_ja is what the form shows.
EPISODE_MODES: dict[str, dict[str, Any]] = {
    "kasumi-late-desk-adult": {
        "label_ja": "霞東フロア あさ",
        "choice_ja": "霞東フロア あさ（迷ったらこれ）",
        "when_ja": "遅刻した朝。4番で行為ルートか戦いルート。5番とシーンごとは無視",
        "recommend": True,
    },
    "hospital-exit-adult": {
        "label_ja": "病棟出口",
        "choice_ja": "病棟出口",
        "when_ja": "感染者の病棟から出口へ。5番が全体の既定。シーンごとで誘う・受け入れる・回避を上書き",
    },
    "bandai-district-short": {
        "label_ja": "番台ショート",
        "choice_ja": "番台ショート（25秒）",
        "when_ja": "25秒・ミッション失敗。理容室だけ新しく描く",
    },
    "bandai-district": {
        "label_ja": "番台フル",
        "choice_ja": "番台フル（92秒）",
        "when_ja": "初回の92秒版。全部描く",
    },
}

EPISODE_ALIASES: dict[str, str] = _label_aliases(
    EPISODE_MODES,
    {
        "霞東": "kasumi-late-desk-adult",
        "霞東あさ": "kasumi-late-desk-adult",
        "kasumi": "kasumi-late-desk-adult",
        "病棟": "hospital-exit-adult",
        "hospital": "hospital-exit-adult",
        "番台短": "bandai-district-short",
        "番台": "bandai-district",
    },
)

# Per-encounter hospital action. inherit = Colab 5番. Fight stories ignore this.
# form=False rows are aliases only (not shown in the dropdown).
SCENE_ACTION_MODES: dict[str, dict[str, Any]] = {
    "inherit": {
        "label_ja": "全体に従う",
        "choice_ja": "全体に従う（迷ったらこれ）",
        "when_ja": "5番の構成をこのシーンでも使う",
        "hint_ja": "迷ったらこれ。戦い構成のときはシーンごとは無視",
        "recommend": True,
        "story": None,
        "pose": None,
    },
    "accept": {
        "label_ja": "受け入れる",
        "choice_ja": "○受け入れる",
        "when_ja": "この人だけ戸惑いながら身体を張る",
        "story": "accept",
        "pose": None,
    },
    "invite_all_fours": {
        "label_ja": "誘う・四つん這い",
        "choice_ja": "□誘う・四つん這い股広げ",
        "when_ja": "この人を四つん這いで誘う",
        "story": "invite",
        "pose": "all_fours",
    },
    "invite_m_open": {
        "label_ja": "誘う・M字",
        "choice_ja": "□誘う・M字開脚仰向け",
        "when_ja": "この人を仰向けM字で誘う",
        "story": "invite",
        "pose": "m_open",
    },
    "invite_ride": {
        "label_ja": "誘う・騎乗",
        "choice_ja": "□誘う・騎乗・足を揃えて立つ",
        "when_ja": "この人を口のあと、足を揃えて立ってから下ろす対面の跨ぎで誘う",
        "story": "invite",
        "pose": "ride",
    },
    "invite_ride_bent": {
        "label_ja": "誘う・騎乗曲げ膝",
        "choice_ja": "□誘う・騎乗・最初から膝曲げ",
        "when_ja": "この人を口のあと、最初から両膝を曲げて下ろす対面の跨ぎで誘う",
        "story": "invite",
        "pose": "ride_bent",
    },
    "invite_stand": {
        "label_ja": "誘う・立ちバック",
        "choice_ja": "□誘う・壁立ちバック",
        "when_ja": "この人を壁に手をついた立ちバックで誘う。横からの肛門",
        "story": "invite",
        "pose": "stand",
    },
    "invite_nelson": {
        "label_ja": "誘う・フルネルソン",
        "choice_ja": "□誘う・フルネルソンアナル",
        "when_ja": "この人の背後からフルネルソン。あやが正面。肛門だけ",
        "story": "invite",
        "pose": "nelson",
    },
    "invite_embrace": {
        "label_ja": "誘う・抱擁",
        "choice_ja": "□誘う・抱擁ベロチュー→壁片足→クンニ→両足抱え",
        "when_ja": "spotの次から抱擁ベロチュー、壁の片足、クンニ、両足抱え",
        "story": "invite",
        "pose": "embrace",
    },
    "invite_jacko": {
        "label_ja": "誘う・後ろアナル",
        "choice_ja": "□誘う・後ろアナル",
        "when_ja": "この人の後ろアナル。顔と胸が床。竿は上から肛門。今の行為は残す",
        "story": "invite",
        "pose": "jacko",
    },
    "evade": {
        "label_ja": "回避",
        "choice_ja": "×回避",
        "when_ja": "この人だけキスですり抜ける",
        "story": "evade",
        "pose": None,
    },
    "invite": {
        "label_ja": "誘う",
        "choice_ja": "□誘う",
        "when_ja": "この人を誘う。ポーズは6番",
        "story": "invite",
        "pose": None,
        "form": False,
    },
}

SCENE_ACTION_ALIASES: dict[str, str] = _label_aliases(
    SCENE_ACTION_MODES,
    {
        "従う": "inherit",
        "default": "inherit",
        "same": "inherit",
        "受け入れる": "accept",
        "誘う": "invite",
        "誘う四つん這い": "invite_all_fours",
        "誘うM字": "invite_m_open",
        "誘う騎乗": "invite_ride",
        "□誘う・対面M字騎乗": "invite_ride",
        "□誘う・騎乗・細い柱": "invite_ride",
        "□誘う・騎乗・足を揃えて立つ": "invite_ride",
        "誘う騎乗曲げ膝": "invite_ride_bent",
        "□誘う・騎乗・曲げ膝": "invite_ride_bent",
        "□誘う・騎乗・最初から膝曲げ": "invite_ride_bent",
        "誘う立ちバック": "invite_stand",
        "誘うフルネルソン": "invite_nelson",
        "誘う抱擁": "invite_embrace",
        "invite-embrace": "invite_embrace",
        "誘う後ろアナル": "invite_jacko",
        "□誘う・後ろアナル": "invite_jacko",
        "invite-jacko": "invite_jacko",
        "□誘う・ベロチュー→じゅぼ→騎乗位": "invite_ride",
        "回避": "evade",
        "invite-all-fours": "invite_all_fours",
        "invite-m-open": "invite_m_open",
        "invite-ride": "invite_ride",
        "invite-stand": "invite_stand",
        "invite-nelson": "invite_nelson",
    },
)


PRESET_ALIASES: dict[str, str] = _label_aliases(
    PRESET_CANON,
    {
        "fast": "speed",
        "preview": "speed",
        "daily": "balance",
        "スピード優先": "speed",
        "質優先": "quality",
    },
)


def expand_presets() -> dict[str, dict[str, Any]]:
    out = dict(PRESET_CANON)
    for alias, canon in PRESET_ALIASES.items():
        if alias.isascii() and alias.isalpha() and alias not in out:
            out[alias] = PRESET_CANON[canon]
    return out


def canonical_preset(name: str) -> str:
    raw = str(name or "").strip()
    if raw in PRESET_CANON:
        return raw
    return PRESET_ALIASES.get(raw, raw)


def canonical_camera(name: str) -> str:
    raw = str(name or "").strip()
    if raw in CAMERA_PACKS:
        return raw
    return CAMERA_ALIASES.get(raw, raw)


def canonical_connect(name: str) -> str:
    raw = str(name or "").strip()
    if not raw:
        return ""
    if raw in CONNECT_MODES:
        return raw
    return CONNECT_ALIASES.get(raw, raw)


def canonical_end_connect(name: str) -> str:
    raw = str(name or "").strip()
    if not raw:
        return ""
    if raw in END_CONNECT_MODES:
        return raw
    return END_CONNECT_ALIASES.get(raw, raw)


def canonical_combat(name: str) -> str:
    raw = str(name or "").strip()
    if not raw:
        return ""
    if raw in COMBAT_MODES:
        return raw
    return COMBAT_ALIASES.get(raw, raw)


def canonical_story(name: str) -> str:
    raw = str(name or "").strip()
    if not raw:
        return ""
    if raw in STORY_MODES:
        return raw
    return STORY_ALIASES.get(raw, raw)


def canonical_invite_pose(name: str) -> str:
    raw = str(name or "").strip()
    if not raw:
        return ""
    if raw in INVITE_POSE_MODES:
        return raw
    return INVITE_POSE_ALIASES.get(raw, raw)


# One person per ride-foot dropdown. Empty means leave that person's scene alone.
RIDE_FOOT_CHOICES: tuple[str, ...] = ("なし", "みき", "れい", "かな", "しの", "ギン", "😈")
RIDE_PERSON_ALIASES: dict[str, str] = {
    "なし": "",
    "none": "",
    "off": "",
    "みき": "miki",
    "miki": "miki",
    "れい": "rei",
    "rei": "rei",
    "かな": "kana",
    "kana": "kana",
    "しの": "shino",
    "shino": "shino",
    "ギン": "gin",
    "gin": "gin",
    "灰色": "gin",
    "😈": "tsuno",
    "角": "tsuno",
    "tsuno": "tsuno",
}
RIDE_PERSON_JA: dict[str, str] = {
    "": "なし",
    "miki": "みき",
    "rei": "れい",
    "kana": "かな",
    "shino": "しの",
    "gin": "ギン",
    "tsuno": "😈",
}


def canonical_ride_person(name: str) -> str:
    """Hospital ride-foot dropdown. '' is なし. Unknown names raise ValueError."""
    raw = str(name or "").strip()
    if not raw:
        return ""
    if raw not in RIDE_PERSON_ALIASES:
        raise ValueError(f"ride person must be one of {list(RIDE_FOOT_CHOICES)}")
    return RIDE_PERSON_ALIASES[raw]


CHECKPOINT_MODES: dict[str, dict[str, Any]] = {
    "eros-max": {
        "label_ja": "10Eros Max",
        "choice_ja": "10Eros Max（既定）",
        "when_ja": "今のエロチェックポイント。迷ったらこれ",
        "recommend": True,
    },
    "dasiwa": {
        "label_ja": "DaSiWa",
        "choice_ja": "DaSiWa Hybrid v2",
        "when_ja": "DaSiWa Hybrid v2。FL2VA と REF2VA。約20GB",
    },
}
CHECKPOINT_ALIASES = {
    "10Eros Max（既定）": "eros-max",
    "10Eros Max": "eros-max",
    "eros": "eros-max",
    "eros-max": "eros-max",
    "DaSiWa Hybrid v2": "dasiwa",
    "DaSiWa": "dasiwa",
    "dasiwa": "dasiwa",
}


def canonical_checkpoint(name: str) -> str:
    raw = str(name or "").strip()
    if not raw:
        return ""
    if raw in CHECKPOINT_MODES:
        return raw
    return CHECKPOINT_ALIASES.get(raw, raw)


def canonical_toilet(name: str) -> str:
    raw = str(name or "").strip()
    if not raw:
        return ""
    if raw in TOILET_MODES:
        return raw
    return TOILET_ALIASES.get(raw, raw)


def canonical_gin(name: str) -> str:
    raw = str(name or "").strip()
    if not raw:
        return ""
    if raw in GIN_MODES:
        return raw
    return GIN_ALIASES.get(raw, raw)


def canonical_tsuno(name: str) -> str:
    raw = str(name or "").strip()
    if not raw:
        return ""
    if raw in TSUNO_MODES:
        return raw
    return TSUNO_ALIASES.get(raw, raw)


def canonical_dog(name: str) -> str:
    raw = str(name or "").strip()
    if not raw:
        return ""
    if raw in DOG_MODES:
        return raw
    return DOG_ALIASES.get(raw, raw)


def canonical_species(name: str) -> str:
    raw = str(name or "").strip()
    if not raw:
        return ""
    if raw in SPECIES_MODES:
        return raw
    return SPECIES_ALIASES.get(raw, raw)


def canonical_rei_mast(name: str) -> str:
    raw = str(name or "").strip()
    if not raw:
        return ""
    if raw in REI_MAST_MODES:
        return raw
    return REI_MAST_ALIASES.get(raw, raw)


def canonical_rei_toilet(name: str) -> str:
    raw = str(name or "").strip()
    if not raw:
        return ""
    if raw in REI_TOILET_MODES:
        return raw
    return REI_TOILET_ALIASES.get(raw, raw)


def canonical_rei_beast(name: str) -> str:
    raw = str(name or "").strip()
    if not raw:
        return ""
    if raw in REI_BEAST_MODES:
        return raw
    return REI_BEAST_ALIASES.get(raw, raw)


def canonical_rei_moth(name: str) -> str:
    raw = str(name or "").strip()
    if not raw:
        return ""
    if raw in REI_MOTH_MODES:
        return raw
    return REI_MOTH_ALIASES.get(raw, raw)


def canonical_rei_attack(name: str) -> str:
    raw = str(name or "").strip()
    if not raw:
        return ""
    if raw in REI_ATTACK_MODES:
        return raw
    return REI_ATTACK_ALIASES.get(raw, raw)


def canonical_rei_kiss(name: str) -> str:
    raw = str(name or "").strip()
    if not raw:
        return ""
    if raw in REI_KISS_MODES:
        return raw
    return REI_KISS_ALIASES.get(raw, raw)


def canonical_rei_oral(name: str) -> str:
    raw = str(name or "").strip()
    if not raw:
        return ""
    if raw in REI_ORAL_MODES:
        return raw
    return REI_ORAL_ALIASES.get(raw, raw)


def canonical_rei_pose(name: str) -> str:
    raw = str(name or "").strip()
    if not raw:
        return ""
    if raw in REI_POSE_MODES:
        return raw
    return REI_POSE_ALIASES.get(raw, raw)


def canonical_encounter(name: str) -> str:
    raw = str(name or "").strip().lower()
    if not raw:
        return ""
    if raw in HOSPITAL_ENCOUNTERS:
        return raw
    return APPEAR_ALIASES.get(raw, raw)


def canonical_episode(name: str) -> str:
    raw = str(name or "").strip()
    if not raw:
        return ""
    if raw in EPISODE_MODES:
        return raw
    return EPISODE_ALIASES.get(raw, raw)


def canonical_scene_action(name: str) -> str:
    raw = str(name or "").strip()
    if not raw:
        return ""
    if raw in SCENE_ACTION_MODES:
        return raw
    return SCENE_ACTION_ALIASES.get(raw, raw)


def split_scene_choice(value: Any) -> tuple[str | None, str | None]:
    """Return (story or None=inherit, pose or None=use Colab 誘うポーズ)."""
    if value in (None, "", False, True):
        return None, None
    if isinstance(value, dict):
        story_raw = str(value.get("story") or "").strip()
        if not story_raw or canonical_scene_action(story_raw) == "inherit":
            return None, None
        key = canonical_scene_action(story_raw) or canonical_story(story_raw)
        spec = SCENE_ACTION_MODES.get(key) if key in SCENE_ACTION_MODES else None
        pose_raw = canonical_invite_pose(str(value.get("pose") or "")) or None
        if spec:
            story = spec.get("story")
            if story in FIGHT_STORIES:
                raise ValueError("scenes cannot pick a fight story")
            return story, pose_raw or spec.get("pose")
        if key in FIGHT_STORIES:
            raise ValueError("scenes cannot pick a fight story")
        if key in STORY_MODES:
            return key, pose_raw
        raise ValueError(f"scenes unknown story {value}")
    key = canonical_scene_action(str(value))
    if not key or key == "inherit":
        return None, None
    spec = SCENE_ACTION_MODES.get(key)
    if not spec:
        raise ValueError(f"scenes unknown choice {value}")
    if spec.get("story") in FIGHT_STORIES:
        raise ValueError("scenes cannot pick a fight story")
    return spec.get("story"), spec.get("pose")


def parse_scenes(raw: str | dict[str, Any] | None) -> dict[str, tuple[str | None, str | None]]:
    """Per-encounter (story, pose). Missing / inherit = (None, None)."""
    out: dict[str, tuple[str | None, str | None]] = {name: (None, None) for name in HOSPITAL_ENCOUNTERS}
    if raw in (None, "", False):
        return out
    items: list[tuple[Any, Any]]
    if isinstance(raw, dict):
        items = list(raw.items())
    else:
        items = []
        for part in str(raw).replace(";", ",").split(","):
            chunk = part.strip()
            if not chunk:
                continue
            if "=" not in chunk:
                raise ValueError(f"scenes expected name=choice, got {chunk}")
            key, value = chunk.split("=", 1)
            items.append((key.strip(), value.strip()))
    for key, value in items:
        enc = canonical_encounter(str(key))
        if enc not in HOSPITAL_ENCOUNTERS:
            raise ValueError(f"scenes unknown encounter {key}")
        out[enc] = split_scene_choice(value)
    return out


def scenes_to_choices(parsed: dict[str, tuple[str | None, str | None]]) -> dict[str, str]:
    """Round-trip parse_scenes() into dropdown keys (inherit / accept / invite_* / evade)."""
    out: dict[str, str] = {}
    for name in HOSPITAL_ENCOUNTERS:
        story, pose = parsed.get(name, (None, None))
        if story is None:
            out[name] = "inherit"
            continue
        found = None
        for key, spec in SCENE_ACTION_MODES.items():
            if spec.get("story") == story and spec.get("pose") == pose:
                found = key
                if spec.get("form", True):
                    break
        out[name] = found or story
    return out


def parse_appear(raw: str | dict[str, Any] | None) -> dict[str, bool]:
    """Which hospital encounters to keep. Empty / missing = all four appear."""
    out = dict(DEFAULT_APPEAR)
    if raw in (None, "", True):
        return out
    if raw is False:
        return {name: False for name in HOSPITAL_ENCOUNTERS}
    if isinstance(raw, dict):
        for key, value in raw.items():
            enc = canonical_encounter(str(key))
            if enc in out:
                out[enc] = bool(value)
        return out
    text = str(raw).strip()
    if not text:
        return out
    if text.lower() in ("all", "全員", "*"):
        return out
    if text.lower() in ("none", "nobody", "0", "なし"):
        return {name: False for name in HOSPITAL_ENCOUNTERS}
    if "," in text or " " in text.replace(",", " "):
        wanted = {canonical_encounter(part) for part in text.replace(",", " ").split() if part.strip()}
        wanted.discard("")
        if wanted:
            return {name: name in wanted for name in HOSPITAL_ENCOUNTERS}
    return out


def _surface(
    choice: str,
    when: str,
    dirt: str,
    env: str,
    wall: str,
    floor: str,
    room: str,
    bed: str,
    edge: str,
    path: str,
    junction: str,
    light: str,
    ambience: str,
    fixture: str,
    priv: str,
    *,
    recommend: bool = False,
) -> dict[str, Any]:
    return {
        "label_ja": choice,
        "choice_ja": choice,
        "when_ja": when,
        "form": True,
        "recommend": recommend,
        "dirt": dirt,
        "env": env,
        "wall": wall,
        "floor": floor,
        "room": room,
        "bed": bed,
        "edge": edge,
        "path": path,
        "junction": junction,
        "light": light,
        "ambience": ambience,
        "fixture": fixture,
        "priv": priv,
    }


# Place swaps nouns in the finished prompt. The hospital key skips that swap.
PLACE_MODES: dict[str, dict[str, Any]] = {
    "hospital": _surface(
        "病棟（迷ったらこれ）", "今の病棟。名詞は替えない", "hospital",
        "", "grey wall", "linoleum", "stall", "mattress", "far long edge nearest the window",
        "corridor", "T-junction", "fluorescent", "fluorescent buzz", "porcelain toilet", "",
        recommend=True,
    ),
    "forest": _surface(
        "森林", "木のあいだの道。床は土", "sand",
        "A fictional forest path at adult height, trunks on both sides, packed earth underfoot, daylight between the trunks",
        "tree trunk", "packed earth", "wooden hut", "mossy log", "far long edge of the mossy log",
        "forest path", "fork in the path", "daylight between the trunks", "wind in the trees",
        "low wooden basin",
        "A small wooden hut among the trunks. Packed earth floor. One low wooden basin. Daylight through the slats",
    ),
    "village": _surface(
        "廃村", "空き家のあいだの土の道", "sand",
        "A fictional abandoned village lane, empty wooden houses, packed earth, an open sky",
        "wooden house wall", "packed earth", "empty house room", "wooden porch", "far edge of the wooden porch",
        "village lane", "fork in the lane", "open daylight", "wind between the houses",
        "low wooden basin",
        "An empty wooden house. Packed earth floor. One low wooden basin. Daylight from the open door",
    ),
    "ruins": _surface(
        "廃墟（外）", "崩れた外壁と瓦礫", "sand",
        "A fictional ruined exterior, broken concrete walls, rubble underfoot, open sky",
        "broken concrete wall", "rubble", "remaining room", "fallen slab", "far edge of the fallen slab",
        "ruin path", "gap in the wall", "open daylight", "wind over the rubble",
        "low concrete basin",
        "A remaining concrete room. Rubble floor. One low concrete basin. Daylight from a hole in the wall",
    ),
    "city": _surface(
        "大都会", "空いた大通り。画面の大人は2人", "soot",
        "A fictional empty city avenue, tall buildings, bare pavement, two adults only",
        "building wall", "bare pavement", "basement room", "concrete bench", "far end of the concrete bench",
        "empty avenue", "street corner", "city daylight", "distant traffic hum",
        "low utility sink",
        "A basement utility room. Bare concrete. One low utility sink. A single bulb",
    ),
    "pool": _surface(
        "プール", "プールサイドと更衣室", "tide",
        "A fictional outdoor pool deck, tile underfoot, still water beside the deck, bright sky",
        "tile wall", "wet tile", "changing room", "deck chair", "far end of the deck chair",
        "pool deck", "corner of the deck", "bright daylight", "water lap",
        "low tile basin",
        "A changing room. Wet tile floor. One low tile basin. Daylight from a high window",
    ),
    "sea": _surface(
        "海", "砂浜と岩陰", "tide",
        "A fictional beach, wet sand, rocks, the waterline beside the path",
        "rock face", "wet sand", "rock alcove", "flat rock", "far edge of the flat rock",
        "beach path", "gap in the rocks", "bright daylight", "surf",
        "tide pool",
        "A rock alcove. Wet sand. One tide pool. Daylight from the opening",
    ),
    "school": _surface(
        "学校", "空き校舎の廊下と階段", "hospital",
        "A fictional empty adult school hallway, painted walls, a hard floor, stairs, high windows",
        "painted wall", "hard floor", "changing room", "cot", "far edge of the cot",
        "hallway", "stair landing", "daylight from high windows", "quiet hallway tone",
        "low wash basin",
        "A changing room. Hard floor. One low wash basin. Daylight from a high window",
    ),
    "office": _surface(
        "オフィス", "パーティションの通路と給湯室", "soot",
        "A fictional office floor, partition walls, tile, a pantry, tall windows",
        "glass wall", "office tile", "pantry", "office sofa", "far end of the office sofa",
        "office aisle", "corner of the aisle", "office daylight", "air vent hum",
        "low pantry sink",
        "A pantry. Office tile. One low pantry sink. Daylight from the aisle",
    ),
    "slum": _surface(
        "スラム", "狭い路地と物置", "soot",
        "A fictional narrow alley, tin walls, packed earth, a shed",
        "tin wall", "packed earth", "shed", "wooden pallet", "far edge of the wooden pallet",
        "narrow alley", "bend in the alley", "alley daylight", "distant alley hum",
        "low metal basin",
        "A tin shed. Packed earth. One low metal basin. Daylight from the alley",
    ),
    "warehouse_town": _surface(
        "城下町・川越", "蔵が続く道。昼は店先、夜は裏路地", "hospital",
        "A fictional warehouse street of plaster kura houses in a row, a wooden lane, shop fronts and a back alley",
        "plaster kura wall", "wooden lane", "kura storeroom", "tatami room", "far edge of the tatami",
        "warehouse lane", "bend into the back alley", "daylight on the shop fronts", "quiet lane tone",
        "low wooden basin",
        "A kura storeroom. Wooden floor. One low wooden basin. Dim light from the lane",
    ),
    "castle": _surface(
        "城・犬山城", "門から天守までが1本の道", "hospital",
        "A fictional small castle, one path from the gate to the keep, stone and wood",
        "stone wall", "wooden floor", "guard alcove", "plank bed", "far edge of the plank bed",
        "castle path", "gate passage", "daylight in the courtyard", "wind in the courtyard",
        "low stone basin",
        "A guard alcove. Wooden floor. One low stone basin. Daylight from the passage",
    ),
    "samurai": _surface(
        "武家屋敷・長町", "格子と用水。夜は暗い庭", "hospital",
        "A fictional samurai house lane, lattice walls, a narrow water channel, a night garden",
        "lattice wall", "packed earth", "store room", "tatami room", "far edge of the tatami",
        "house lane", "corner by the water channel", "dim garden light", "water in the channel",
        "low wooden basin",
        "A store room. Wooden floor. One low wooden basin. Dim light from the garden",
    ),
    "shrine": _surface(
        "神社・千本鳥居", "鳥居の続く参道。奥ほど暗い", "sand",
        "A fictional shrine path of repeated torii gates, stone steps, darker toward the far end",
        "torii post", "stone step", "shrine shed", "stone platform", "far edge of the stone platform",
        "torii path", "landing on the steps", "dim light under the gates", "wind through the gates",
        "low stone basin",
        "A shrine shed. Stone floor. One low stone basin. Dim light from the path",
    ),
    "temple": _surface(
        "寺院・建長寺", "庭が手前、本堂が奥", "sand",
        "A fictional temple garden, raked gravel, white walls, a main hall at the far end",
        "white wall", "raked gravel", "kitchen alcove", "veranda", "far edge of the veranda",
        "garden path", "step up to the hall", "daylight in the garden", "wind in the garden",
        "low stone basin",
        "A kitchen alcove. Wooden floor. One low stone basin. Daylight from the garden",
    ),
    "bamboo": _surface(
        "竹林・報国寺", "見通しの悪い竹", "sand",
        "A fictional bamboo grove, close stalks, packed earth, short sight lines",
        "bamboo stalk", "packed earth", "small pavilion", "mossy floor", "far edge of the moss",
        "bamboo path", "bend in the bamboo", "dim daylight through the stalks", "wind in the bamboo",
        "low stone basin",
        "A small pavilion. Packed earth. One low stone basin. Dim daylight through the stalks",
    ),
    "cemetery": _surface(
        "霊廟・奥之院", "杉と墓標の直線", "sand",
        "A fictional cedar approach lined with stone markers, a straight path, a hall at the far end",
        "cedar trunk", "packed earth", "covered shelter", "stone platform", "far edge of the stone platform",
        "cedar path", "gap in the markers", "dim daylight under the cedars", "wind in the cedars",
        "low stone basin",
        "A covered shelter. Stone floor. One low stone basin. Dim daylight from the path",
    ),
    "onsen": _surface(
        "温泉街・有馬", "石段。湯気のたまる段", "steam",
        "A fictional hot-spring stair street, stone steps, steam over one landing, wooden walls",
        "wooden wall", "wet stone step", "changing hut", "rock ledge", "far edge of the rock ledge",
        "stone stair", "steaming landing", "soft daylight through steam", "water over stone",
        "hot-spring basin",
        "A changing hut. Wet stone. One hot-spring basin. Steam and soft daylight",
    ),
    "port": _surface(
        "港町・尾道", "坂そのものが道", "tide",
        "A fictional harbor slope of stone steps between houses, the water below",
        "house wall", "stone step", "landing shed", "wooden bench", "far end of the wooden bench",
        "harbor slope", "turn in the steps", "harbor daylight", "water below the slope",
        "low stone basin",
        "A landing shed. Stone floor. One low stone basin. Daylight from the slope",
    ),
    "canal": _surface(
        "運河・小樽", "倉庫と水面。夜は暗い岸", "tide",
        "A fictional canal, stone warehouses, a paved quay, still water beside the path",
        "warehouse wall", "stone quay", "warehouse room", "stone ledge", "far edge of the stone ledge",
        "canal quay", "bridge mouth", "dim light on the quay", "water against stone",
        "low stone basin",
        "A warehouse room. Stone floor. One low stone basin. Dim light from the quay",
    ),
    "sea_cave": _surface(
        "海蝕洞・江の島", "入口が明るく、奥が狭い", "tide",
        "A fictional sea cave, a bright mouth, a narrow darker passage, wet rock",
        "wet rock wall", "wet sand", "inner hollow", "rock shelf", "far edge of the rock shelf",
        "cave passage", "narrowing of the cave", "daylight from the cave mouth", "water drip",
        "tide pool",
        "An inner hollow. Wet sand. One tide pool. Dim light from the passage",
    ),
    "buddha_cave": _surface(
        "宗教窟・鋸山", "磨崖と洞", "hospital",
        "A fictional cliff cave, carved stone figures in the rock, a hollow passage",
        "carved rock wall", "stone floor", "side hollow", "rock shelf", "far edge of the rock shelf",
        "cliff passage", "mouth of a side hollow", "dim daylight from the cliff", "wind in the hollow",
        "low stone basin",
        "A side hollow. Stone floor. One low stone basin. Dim daylight from the passage",
    ),
    "limestone": _surface(
        "鍾乳洞・日原", "低い天井と水音", "tide",
        "A fictional limestone cave, a low ceiling, wet stone, water sounds",
        "wet limestone wall", "wet stone", "inner chamber", "rock shelf", "far edge of the rock shelf",
        "cave passage", "low bend", "dim reflected light", "water drip",
        "shallow pool",
        "An inner chamber. Wet stone. One shallow pool. Dim reflected light",
    ),
    "mine": _surface(
        "坑道・佐渡", "枕木とレール。手元の光", "soot",
        "A fictional mine tunnel, sleepers and a rail, rock walls, a headlamp pool of light",
        "rock wall", "wooden sleepers", "side chamber", "ore cart", "far edge of the ore cart",
        "mine tunnel", "junction of the rail", "headlamp light", "distant tunnel tone",
        "low metal basin",
        "A side chamber. Wooden sleepers. One low metal basin. Headlamp light",
    ),
    "ice": _surface(
        "氷穴・富岳", "冷気の岩穴", "hospital",
        "A fictional ice cave, frost on the rock, cold air, pale light",
        "frosted rock wall", "frosted stone", "ice alcove", "ice shelf", "far edge of the ice shelf",
        "ice passage", "bend in the ice", "pale cold light", "cold air tone",
        "low ice basin",
        "An ice alcove. Frosted stone. One low ice basin. Pale cold light",
    ),
    "volcano": _surface(
        "火山・大涌谷", "遊歩道。噴気の先が境界", "soot",
        "A fictional volcanic walkway, warm rock, steam vents ahead as the boundary",
        "rock wall", "warm rock", "shelter", "rock ledge", "far edge of the rock ledge",
        "volcanic walkway", "end of the walkway", "hazy daylight", "steam vent hiss",
        "low stone basin",
        "A shelter. Warm rock floor. One low stone basin. Hazy daylight",
    ),
    "battleship": _surface(
        "廃都・軍艦島", "コンクリートと海", "soot",
        "A fictional concrete island, broken blocks, the sea beside the path",
        "concrete wall", "concrete", "remaining room", "concrete slab", "far edge of the concrete slab",
        "concrete path", "gap between blocks", "sea daylight", "surf on concrete",
        "low concrete basin",
        "A remaining concrete room. Concrete floor. One low concrete basin. Sea daylight from a hole",
    ),
    "mine_town": _surface(
        "閉山集落・池島", "坑口と団地が残る", "soot",
        "A fictional closed mining village, apartment blocks, a tunnel mouth, packed earth",
        "concrete wall", "packed earth", "empty apartment", "apartment floor", "far edge of the apartment floor",
        "village path", "tunnel mouth", "overcast daylight", "wind between the blocks",
        "low metal basin",
        "An empty apartment. Concrete floor. One low metal basin. Overcast daylight from a window",
    ),
    "factory": _surface(
        "工場・京浜", "配管と高架の工業区", "soot",
        "A fictional factory district at night-adjacent dusk, pipes, an overpass, concrete",
        "steel wall", "concrete", "locker room", "work table", "far edge of the work table",
        "factory lane", "gate", "industrial lamps", "machine hum",
        "low metal basin",
        "A locker room. Concrete floor. One low metal basin. An industrial lamp",
    ),
    "overpass": _surface(
        "高架下・汐留", "柱の反復と車の光", "soot",
        "A fictional underpass, repeated columns, pavement, streaks of car light",
        "concrete column", "pavement", "utility room", "concrete ledge", "far edge of the concrete ledge",
        "underpass", "gap between columns", "car light", "traffic overhead",
        "low utility sink",
        "A utility room. Pavement. One low utility sink. Car light from the underpass",
    ),
}

TIME_MODES: dict[str, dict[str, Any]] = {
    "night": {
        "label_ja": "夜",
        "choice_ja": "夜（迷ったらこれ）",
        "when_ja": "今の病棟の夜。文は足さない",
        "form": True,
        "recommend": True,
        "sentence": "",
        "away": "The light stays low.",
    },
    "morning": {
        "label_ja": "朝",
        "choice_ja": "朝",
        "when_ja": "低い光。行為は変えない",
        "form": True,
        "sentence": "Low morning sun lights the ground. The light stays soft.",
        "away": "Low morning sun lights the ground. The light stays soft.",
    },
    "day": {
        "label_ja": "昼",
        "choice_ja": "昼",
        "when_ja": "高い光。行為は変えない",
        "form": True,
        "sentence": "High daylight lights the ground. The ground stays brightly lit.",
        "away": "High daylight lights the ground. The ground stays brightly lit.",
    },
}

WEATHER_MODES: dict[str, dict[str, Any]] = {
    "off": {
        "label_ja": "指定なし",
        "choice_ja": "天候なし（迷ったらこれ）",
        "when_ja": "天候の文は足さない",
        "form": True,
        "recommend": True,
        "sentence": "",
    },
    "clear": {
        "label_ja": "晴れ",
        "choice_ja": "晴れ",
        "when_ja": "乾いた床と澄んだ光",
        "form": True,
        "sentence": "The ground stays dry. The light stays clear.",
    },
    "rain": {
        "label_ja": "雨",
        "choice_ja": "雨",
        "when_ja": "濡れた床と暗い光",
        "form": True,
        "sentence": "The ground is wet. The light stays dim.",
    },
    "fog": {
        "label_ja": "霧",
        "choice_ja": "霧",
        "when_ja": "近い床と薄い光",
        "form": True,
        "sentence": "The ground nearby stays visible. The light stays pale and thick.",
    },
    "snow": {
        "label_ja": "雪",
        "choice_ja": "雪",
        "when_ja": "白い床と冷たい光",
        "form": True,
        "sentence": "A white layer covers the ground. The light stays cold and bright.",
    },
}

DIRT_MODES: dict[str, dict[str, Any]] = {
    "place": {
        "label_ja": "場所に合わせる",
        "choice_ja": "場所に合わせる（迷ったらこれ）",
        "when_ja": "病棟なら今の汚れ。別の場所ならその場所の汚れ",
        "form": True,
        "recommend": True,
        "phrase": "",
    },
    "hospital": {
        "label_ja": "病院の汚れ",
        "choice_ja": "病院の汚れ",
        "when_ja": "今の病院の汚れのまま",
        "form": True,
        "phrase": "",
    },
    "sand": {
        "label_ja": "砂",
        "choice_ja": "砂",
        "when_ja": "あやの病院の汚れを砂に替える。傷は残す",
        "form": True,
        "phrase": "fine dry sand clinging to the skin",
    },
    "tide": {
        "label_ja": "潮",
        "choice_ja": "潮",
        "when_ja": "あやの病院の汚れを潮の膜に替える。傷は残す",
        "form": True,
        "phrase": "a seawater sheen and fine salt on the skin",
    },
    "soot": {
        "label_ja": "煤",
        "choice_ja": "煤",
        "when_ja": "あやの病院の汚れを煤に替える。傷は残す",
        "form": True,
        "phrase": "black soot clinging to the skin",
    },
    "steam": {
        "label_ja": "湯気",
        "choice_ja": "湯気",
        "when_ja": "あやの病院の汚れを湯の膜に替える。傷は残す",
        "form": True,
        "phrase": "a wet mineral sheen on the skin",
    },
}

CAMERA_DISTANCE_MODES: dict[str, dict[str, Any]] = {
    "side": {
        "label_ja": "横固定",
        "choice_ja": "横固定（迷ったらこれ）",
        "when_ja": "今の真横・全身の固定文",
        "form": True,
        "recommend": True,
        "lock": "",
    },
    "low": {
        "label_ja": "低い見上げ",
        "choice_ja": "結合の低い見上げ",
        "when_ja": "結合が中央。口と顔射は今の距離",
        "form": True,
        "lock": (
            "Low camera between the calves, looking slightly up. The join stays at the center of the frame. "
            "Adults stay on this same floor spot at normal adult human height, same scale as a standing adult woman. "
            "The feet stay on this floor mark. The camera HOLDS. "
            "Both adults stay in frame from the shoulders to the feet"
        ),
    },
    "wide": {
        "label_ja": "全身の引き",
        "choice_ja": "全身の引き",
        "when_ja": "頭から両足まで。口と顔射は今の距離",
        "form": True,
        "lock": (
            "Pulled-back camera. Both adults stay full body including both heads and all four feet. "
            "Adults stay on this same floor spot at normal adult human height, same scale as a standing adult woman. "
            "The feet stay on this floor mark. The camera HOLDS"
        ),
    },
}

PLACE_ALIASES = _label_aliases(PLACE_MODES, {})
TIME_ALIASES = _label_aliases(TIME_MODES, {"朝方": "morning"})
WEATHER_ALIASES = _label_aliases(WEATHER_MODES, {})
DIRT_ALIASES = _label_aliases(DIRT_MODES, {})
CAMERA_DISTANCE_ALIASES = _label_aliases(CAMERA_DISTANCE_MODES, {"引き": "wide", "低め": "low"})

HOSPITAL_ENV_HEAD = (
    "Fictional derelict old hospital at night, worn down by a fictional pandemic: "
    "crumbling peeling beige walls, cracked stained grey linoleum, rusted rails, "
    "rubber doors hanging loose, flickering broken fluorescent tubes, water stains, a dark far end"
)
TOILET_ENV_BLOCK = (
    "A filthy crumbling western hospital toilet at night. Cracked grey tiles. Peeling plaster. "
    "One stained white porcelain toilet with a seat and a bowl, covered in extra-viscous sticky grimy brown hospital dirt "
    "and brown smears. The seat, the bowl, and the tiles stay smeared. A flickering broken fluorescent tube."
)


def _canon(registry: dict[str, dict[str, Any]], aliases: dict[str, str], name: str) -> str:
    raw = str(name or "").strip()
    if not raw:
        return ""
    if raw in registry:
        return raw
    return aliases.get(raw, "")


def canonical_place(name: str) -> str:
    return _canon(PLACE_MODES, PLACE_ALIASES, name)


def canonical_time(name: str) -> str:
    return _canon(TIME_MODES, TIME_ALIASES, name)


def canonical_weather(name: str) -> str:
    return _canon(WEATHER_MODES, WEATHER_ALIASES, name)


def canonical_dirt(name: str) -> str:
    return _canon(DIRT_MODES, DIRT_ALIASES, name)


def canonical_camera_distance(name: str) -> str:
    return _canon(CAMERA_DISTANCE_MODES, CAMERA_DISTANCE_ALIASES, name)


def dirt_phrase_for(place_key: str, dirt_key: str) -> str:
    """English dirt clause. Empty leaves the authored hospital dirt."""
    dirt = dirt_key or "place"
    if dirt == "place":
        if not place_key or place_key == "hospital":
            return ""
        dirt = str(PLACE_MODES.get(place_key, {}).get("dirt") or "hospital")
    return str((DIRT_MODES.get(dirt) or {}).get("phrase") or "")


LOOK_MODES: dict[str, dict[str, Any]] = {
    "keep": {
        "label_ja": "今のまま",
        "choice_ja": "今のまま（迷ったらこれ）",
        "when_ja": "台本の見た目。自由記入は使わない",
        "form": True,
        "recommend": True,
        "hair": "",
        "face": "",
    },
    "jp": {
        "label_ja": "日本",
        "choice_ja": "日本",
        "when_ja": "黒髪のストレート、やわらかい面長",
        "form": True,
        "hair": "long straight black hair past the shoulders, blunt bangs across the forehead",
        "face": "soft oval face, dark brown eyes, thin eyebrows, soft pink lips, fair skin",
    },
    "kr": {
        "label_ja": "韓国",
        "choice_ja": "韓国",
        "when_ja": "黒髪のロング、小さい顔",
        "form": True,
        "hair": "long straight glossy black hair past the shoulders",
        "face": "small oval face, dark monolid eyes, straight nose, soft pink lips, fair skin",
    },
    "cn": {
        "label_ja": "中国",
        "choice_ja": "中国",
        "when_ja": "黒いまとめ髪、切れ長",
        "form": True,
        "hair": "long black hair gathered in a low twist",
        "face": "oval face, dark almond eyes, defined brows, soft lips, fair skin",
    },
    "sea": {
        "label_ja": "東南アジア",
        "choice_ja": "東南アジア",
        "when_ja": "暗いウェーブ、丸みのある顔",
        "form": True,
        "hair": "long dark wavy hair past the shoulders",
        "face": "round soft face, dark brown eyes, full lips, warm tan skin",
    },
    "south_asia": {
        "label_ja": "南アジア",
        "choice_ja": "南アジア",
        "when_ja": "暗いロング、大きな目",
        "form": True,
        "hair": "long thick dark hair past the shoulders",
        "face": "oval face, large dark eyes, defined brows, full lips, warm brown skin",
    },
    "mideast": {
        "label_ja": "中東",
        "choice_ja": "中東",
        "when_ja": "暗いウェーブ、高い鼻",
        "form": True,
        "hair": "long dark wavy hair past the shoulders",
        "face": "oval face, dark eyes, a high nose, full lips, olive skin",
    },
    "north_eu": {
        "label_ja": "北欧",
        "choice_ja": "北欧",
        "when_ja": "金髪、色の薄い目",
        "form": True,
        "hair": "long straight blonde hair past the shoulders",
        "face": "oval face, light blue eyes, pale brows, soft lips, fair skin",
    },
    "south_eu": {
        "label_ja": "南欧",
        "choice_ja": "南欧",
        "when_ja": "茶色のウェーブ、オリーブの肌",
        "form": True,
        "hair": "long wavy brown hair past the shoulders",
        "face": "oval face, dark brown eyes, defined brows, full lips, olive skin",
    },
    "africa": {
        "label_ja": "アフリカ",
        "choice_ja": "アフリカ",
        "when_ja": "黒いカール、深い肌",
        "form": True,
        "hair": "long dark curly hair past the shoulders",
        "face": "oval face, dark brown eyes, full lips, deep brown skin",
    },
    "latin": {
        "label_ja": "ラテンアメリカ",
        "choice_ja": "ラテンアメリカ",
        "when_ja": "暗いウェーブ、暖かい肌",
        "form": True,
        "hair": "long dark wavy hair past the shoulders",
        "face": "oval face, dark brown eyes, full lips, warm tan skin",
    },
    "other": {
        "label_ja": "その他",
        "choice_ja": "その他",
        "when_ja": "このときだけ自由記入を使う",
        "form": True,
        "hair": "",
        "face": "",
    },
}

ENEMY_KIND_MODES: dict[str, dict[str, Any]] = {
    "zombie": {
        "label_ja": "ゾンビ",
        "choice_ja": "ゾンビ（迷ったらこれ）",
        "when_ja": "今の感染姿。紫、傷、空洞の目",
        "form": True,
        "recommend": True,
    },
    "human": {
        "label_ja": "人間",
        "choice_ja": "人間",
        "when_ja": "腐りと紫と空洞の目を外す。竿の長さ、しのの長身、角の角と一つの目は残す",
        "form": True,
    },
}

LOOK_ALIASES = _label_aliases(LOOK_MODES, {"今のあや": "keep", "今の敵": "keep"})
ENEMY_KIND_ALIASES = _label_aliases(ENEMY_KIND_MODES, {})


def canonical_look(name: str) -> str:
    return _canon(LOOK_MODES, LOOK_ALIASES, name)


def canonical_enemy_kind(name: str) -> str:
    return _canon(ENEMY_KIND_MODES, ENEMY_KIND_ALIASES, name)


def _registry(kind: str) -> dict[str, dict[str, Any]]:
    if kind == "connect":
        return CONNECT_MODES
    if kind == "end_connect":
        return END_CONNECT_MODES
    if kind == "camera":
        return CAMERA_PACKS
    if kind == "place":
        return PLACE_MODES
    if kind == "time":
        return TIME_MODES
    if kind == "weather":
        return WEATHER_MODES
    if kind == "dirt":
        return DIRT_MODES
    if kind == "camera_distance":
        return CAMERA_DISTANCE_MODES
    if kind == "look":
        return LOOK_MODES
    if kind == "enemy_kind":
        return ENEMY_KIND_MODES
    if kind == "preset":
        return PRESET_CANON
    if kind == "combat":
        return COMBAT_MODES
    if kind == "story":
        return STORY_MODES
    if kind == "invite_pose":
        return INVITE_POSE_MODES
    if kind == "checkpoint":
        return CHECKPOINT_MODES
    if kind == "toilet":
        return TOILET_MODES
    if kind == "gin":
        return GIN_MODES
    if kind == "tsuno":
        return TSUNO_MODES
    if kind == "dog":
        return DOG_MODES
    if kind == "species":
        return SPECIES_MODES
    if kind == "rei_mast":
        return REI_MAST_MODES
    if kind == "rei_toilet":
        return REI_TOILET_MODES
    if kind == "rei_beast":
        return REI_BEAST_MODES
    if kind == "rei_moth":
        return REI_MOTH_MODES
    if kind == "rei_attack":
        return REI_ATTACK_MODES
    if kind == "rei_kiss":
        return REI_KISS_MODES
    if kind == "rei_oral":
        return REI_ORAL_MODES
    if kind == "rei_pose":
        return REI_POSE_MODES
    if kind == "episode":
        return EPISODE_MODES
    if kind == "scene":
        return {key: spec for key, spec in SCENE_ACTION_MODES.items() if spec.get("form", True)}
    raise KeyError(kind)


def _shown_specs(kind: str):
    """Dropdown rows. form=False stays as an alias and stays off the list."""
    return [spec for spec in _registry(kind).values() if spec.get("form", True)]


def ui_choices(kind: str) -> list[str]:
    """Japanese dropdown strings for Colab, in display order."""
    return [str(spec.get("choice_ja") or spec["label_ja"]) for spec in _shown_specs(kind)]


def ui_default(kind: str) -> str:
    """The recommended dropdown value (迷ったらこれ)."""
    for spec in _shown_specs(kind):
        if spec.get("recommend"):
            return str(spec.get("choice_ja") or spec["label_ja"])
    return ui_choices(kind)[0]


def form_markdown(kind: str, heading: str) -> str:
    """Colab #@markdown bullets: each option plus when to pick it."""
    lines = [f"#@markdown **{heading}**"]
    for spec in _shown_specs(kind):
        choice = spec.get("choice_ja") or spec["label_ja"]
        when = spec.get("when_ja") or spec.get("hint_ja")
        lines.append(f"#@markdown - **{choice}** … {when}")
    return "\n".join(lines)


def form_readme(kind: str) -> str:
    """Markdown bullets for the notebook intro / README (no #@markdown prefix)."""
    lines = []
    for spec in _shown_specs(kind):
        choice = spec.get("choice_ja") or spec["label_ja"]
        when = spec.get("when_ja") or spec.get("hint_ja")
        lines.append(f"- **{choice}** … {when}")
    return "\n".join(lines)


def describe_run(
    *,
    connect: str = "",
    end_connect: str = "",
    camera: str = "",
    preset: str = "",
    combat: str = "",
    story: str = "",
    invite_pose: str = "",
    toilet: str = "",
    gin: str = "",
    tsuno: str = "",
    dog: str = "",
    species: str = "",
    appear: str | dict[str, Any] | None = None,
    scenes: str | dict[str, Any] | None = None,
    episode: str = "",
    rei_mast: str = "",
    rei_toilet: str = "",
    rei_beast: str = "",
    rei_moth: str = "",
    rei_attack: str = "",
    rei_kiss: str = "",
    rei_oral: str = "",
    rei_pose: str = "",
    ride_bent: str = "",
    ride_column: str = "",
) -> str:
    """One short Japanese block at run start: what was chosen and when to pick something else."""
    c_key = canonical_connect(connect) or DEFAULT_CONNECT
    e_key = canonical_end_connect(end_connect) or "t2v"
    cam_key = canonical_camera(camera) or DEFAULT_CAMERA_PACK
    p_key = canonical_preset(preset) or "balance"
    f_key = canonical_combat(combat) or "off"
    s_key = canonical_story(story) or "accept"
    pose_key = canonical_invite_pose(invite_pose) or "all_fours"
    t_key = canonical_toilet(toilet) or "off"
    g_key = canonical_gin(gin) or "off"
    n_key = canonical_tsuno(tsuno) or "off"
    d_key = canonical_dog(dog) or "off"
    sp_key = canonical_species(species) or "off"
    shown = parse_appear(appear)
    c = CONNECT_MODES.get(c_key) or CONNECT_MODES[DEFAULT_CONNECT]
    e = END_CONNECT_MODES.get(e_key) or END_CONNECT_MODES["t2v"]
    cam = CAMERA_PACKS.get(cam_key) or CAMERA_PACKS[DEFAULT_CAMERA_PACK]
    p = PRESET_CANON.get(p_key) or PRESET_CANON["balance"]
    f = COMBAT_MODES.get(f_key) or COMBAT_MODES["off"]
    s = STORY_MODES.get(s_key) or STORY_MODES["accept"]
    pose = INVITE_POSE_MODES.get(pose_key) or INVITE_POSE_MODES["all_fours"]
    t = TOILET_MODES.get(t_key) or TOILET_MODES["off"]
    g = GIN_MODES.get(g_key) or GIN_MODES["off"]
    n = TSUNO_MODES.get(n_key) or TSUNO_MODES["off"]
    d = DOG_MODES.get(d_key) or DOG_MODES["off"]
    sp = SPECIES_MODES.get(sp_key) or SPECIES_MODES["off"]
    appear_ja = " ".join(("○" if shown[name] else "×") + name for name in HOSPITAL_ENCOUNTERS)
    parsed = parse_scenes(scenes)
    scene_bits = []
    for name in HOSPITAL_ENCOUNTERS:
        story_key, pose_key = parsed[name]
        if story_key is None:
            scene_bits.append(ENCOUNTER_LABEL_JA[name] + "従う")
            continue
        label = story_key
        for spec in SCENE_ACTION_MODES.values():
            if spec.get("story") == story_key and spec.get("pose") == pose_key and spec.get("form", True):
                label = str(spec.get("label_ja") or story_key)
                break
        scene_bits.append(ENCOUNTER_LABEL_JA[name] + label)
    scenes_ja = " ".join(scene_bits)
    slug = canonical_episode(episode) or episode
    ep_spec = EPISODE_MODES.get(slug)
    ep_ja = str(ep_spec["choice_ja"]) if ep_spec else (slug or "一発")
    head = f"一発 {ep_ja}".strip()
    if slug == "futanari-rei-escape":
        rm = REI_MAST_MODES.get(canonical_rei_mast(rei_mast) or "skip") or REI_MAST_MODES["skip"]
        rt = REI_TOILET_MODES.get(canonical_rei_toilet(rei_toilet) or "ta") or REI_TOILET_MODES["ta"]
        rb = REI_BEAST_MODES.get(canonical_rei_beast(rei_beast) or "accept") or REI_BEAST_MODES["accept"]
        rmo = REI_MOTH_MODES.get(canonical_rei_moth(rei_moth) or "tail") or REI_MOTH_MODES["tail"]
        ra = REI_ATTACK_MODES.get(canonical_rei_attack(rei_attack) or "rei") or REI_ATTACK_MODES["rei"]
        rk = REI_KISS_MODES.get(canonical_rei_kiss(rei_kiss) or "off") or REI_KISS_MODES["off"]
        ro = REI_ORAL_MODES.get(canonical_rei_oral(rei_oral) or "skip") or REI_ORAL_MODES["skip"]
        rp = REI_POSE_MODES.get(canonical_rei_pose(rei_pose) or "fours") or REI_POSE_MODES["fours"]
        return (
            f"{head}\n"
            f"  話        ふたなりレイ脱出\n"
            f"  1 つなぎ  {c['choice_ja']}  — {c['when_ja']}\n"
            f"  2 カメラ  {cam['choice_ja']}  — {cam['when_ja']}\n"
            f"  3 画質    {p['choice_ja']}  — {p['when_ja']}\n"
            f"  4 格闘    {f['choice_ja']}  — {f['when_ja']}\n"
            f"  5 合間    {rm['choice_ja']}  — {rm['when_ja']}\n"
            f"  6 トイレ  {rt['choice_ja']}  — {rt['when_ja']}\n"
            f"  7 敵1     {rb['choice_ja']}  — {rb['when_ja']}\n"
            f"  8 蛾女    {rmo['choice_ja']}  — {rmo['when_ja']}\n"
            f"  9 襲う    {ra['choice_ja']}  — {ra['when_ja']}\n"
            f"  10 キス   {rk['choice_ja']}  — {rk['when_ja']}\n"
            f"  11 口     {ro['choice_ja']}  — {ro['when_ja']}\n"
            f"  12 挿入   {rp['choice_ja']}  — {rp['when_ja']}\n"
            "迷ったら既定のままで Run all。病棟の話ではない。カメラは各カットが真横固定。10は顔のキス、11はフェラかクンニ。"
        )
    return (
        f"{head}\n"
        f"  話        {ep_ja}\n"
        f"  1 つなぎ  {c['choice_ja']}  — {c['when_ja']}\n"
        f"  2 カメラ  {cam['choice_ja']}  — {cam['when_ja']}\n"
        f"  3 画質    {p['choice_ja']}  — {p['when_ja']}\n"
        f"  4 格闘    {f['choice_ja']}  — {f['when_ja']}\n"
        f"  5 構成    {s['choice_ja']}  — {s['when_ja']}\n"
        f"  6 誘う    {pose['choice_ja']}  — {pose['when_ja']}\n"
        f"  騎乗曲げ  {RIDE_PERSON_JA.get(ride_bent, ride_bent or 'なし')}\n"
        f"  騎乗柱    {RIDE_PERSON_JA.get(ride_column, ride_column or 'なし')}\n"
        f"  7 トイレ  {t['choice_ja']}  — {t['when_ja']}\n"
        f"  8 灰色    {g['choice_ja']}  — {g['when_ja']}\n"
        f"  9 角      {n['choice_ja']}  — {n['when_ja']}\n"
        f"  10 犬     {d['choice_ja']}  — {d['when_ja']}\n"
        f"  11 異種   {sp['choice_ja']}  — {sp['when_ja']}\n"
        f"  登場      {appear_ja}\n"
        f"  シーン    {scenes_ja}\n"
        "迷ったら既定のままで Run all。新しい相手の入りはカット。消滅はチェーンならフェード。8から11は病棟の追加オプション。スライムとケモノは同時に出ない。シーンごとは病棟だけ。戦い構成のときはシーンごとは無視。"
    )
