"""Additive registries for H3 episode trailers.

Stories stay as `minimaxh3/episodes/<slug>/episode.json`. Do not edit this file
to add a plot. Copy `_template` (or an adult pack) and change the JSON.

Add a camera here: one key + lock + angles. Adjacent T2V shots rotate angles
so each clip can be prompt-corrected instead of last-frame chained.

Add a speed/quality tradeoff here: one key + LoRA stack + steps + sampler.
Cinema LoRA is not a preset (heavy, slow). Combat is never a preset; fight
beats opt in with extra_loras: ["combat"].
"""

from __future__ import annotations

from typing import Any

# Default when a T2V episode omits render.camera_pack.
DEFAULT_CAMERA_PACK = "side2d"

# Positive phrasing only. Named "slow motion" (even negated) still gets drawn.
CAMERA_PACKS: dict[str, dict[str, Any]] = {
    "side2d": {
        "lock": (
            "Locked side-on 2D side-scroller third-person gameplay camera at hip-to-shoulder height. "
            "Both adults stay full body including feet. The camera stays in the side plane and tracks "
            "only left and right on a straight line at real-time game speed"
        ),
        "angles": (
            "locked side-on wide at hip height, both adults full body including feet, horizontal track only",
            "locked side-on at shoulder height, a half-step closer, both adults full body including feet, same side plane",
            "locked side-on further back so more floor shows, hip height, both adults full body including feet, horizontal track only",
            "locked side-on at desk height, both adults full body, same side plane, slight horizontal track",
            "locked side-on wide at chest height, both adults full body including feet, camera holds then tracks left and right",
        ),
    },
    "action3d": {
        "lock": (
            "Pulled-back third-person 3D-action gameplay camera. Both adults stay full body including feet. "
            "The camera stays behind or beside the player at hip-to-shoulder height at real-time game speed"
        ),
        "angles": (
            "behind-left three-quarter at shoulder height, pulled back, both adults full body including feet",
            "behind-right three-quarter at hip height, pulled back, both adults full body including feet",
            "high three-quarter over the aisle, pulled back, both adults full body including feet",
            "low three-quarter at hip height tracking the lead adult, both adults full body including feet",
            "side-rear three-quarter at shoulder height, pulled back, both adults full body including feet",
        ),
    },
}

# User-facing names. Aliases keep older episode.json valid.
# stack entries are (lora_key, strength, optional). Larry never stacks with LightX2V turbo.
PRESET_CANON: dict[str, dict[str, Any]] = {
    "speed": {
        "stack": [("turbo4", 1.0, False)],
        "steps": 4,
        "trigger": "",
        "sampler": "euler",
        "scheduler": "simple",
    },
    "balance": {
        "stack": [("larry", 1.0, False)],
        "steps": 8,
        "trigger": "",
        "sampler": "euler",
        "scheduler": "simple",
    },
    "quality": {
        "stack": [("larry", 1.0, False)],
        "steps": 12,
        "trigger": "",
        "sampler": "euler",
        "scheduler": "beta",
    },
}

PRESET_ALIASES: dict[str, str] = {
    "fast": "speed",
    "preview": "speed",
    "daily": "balance",
}


def expand_presets() -> dict[str, dict[str, Any]]:
    out = dict(PRESET_CANON)
    for alias, canon in PRESET_ALIASES.items():
        out[alias] = PRESET_CANON[canon]
    return out


def canonical_preset(name: str) -> str:
    return PRESET_ALIASES.get(name, name)
